### ISSUE TITLE
Service LB and Loading Lots of Data via PySpark

### ISSUE THREAD

**Issue by bradenwright** [elastic/cloud-on-k8s#1445]
## Bug Report
**What did you do?**
Setup an ES cluster inside K8s, exposed data nodes via Service LB.  I'm trying to run a job in GCP dataproc that uses pyspark / spark to write to ES.  It writes a lot of docs but I'm seeing Connection error after a while.  Also seems to have a lot more documents in the index than the ES cluster we have setup on VMs

**What did you expect to see?**
All data loaded into ES without errors.  I was expecting 3.4 mill record in the index, currently there is over 4 mill, and more than 1/2 of the write Jobs failed.

**What did you see instead? Under which circumstances?**
```
Writing AL to Elastic Search 35.224.92.128 Index al_deduped
19/07/31 22:30:56 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 57.0 in stage 42.0 (TID 10186, sidm-stew-00-w-8.c.site-impact-infra.internal, executor 125): org.apache.spark.util.TaskCompletionListenerException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[35.224.92.128:9200]] 
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:138)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:116)
	at org.apache.spark.scheduler.Task.run(Task.scala:137)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Environment**

* Version information:

	ECK 0.8.1

* Kubernetes information:
`1.13.7-gke.8`
	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```
v1.15.1
```

Code to insert into ES:

```
        df.write.mode('append').format('org.elasticsearch.spark.sql')\
            .option('es.nodes', ES_HOST)\
            .option('es.port', 9200)\
            .option('es.resource', '%s/%s' % (ES_INDEX, '_doc'))\
            .option("es.net.ssl", "true") \
            .option("es.net.ssl.cert.allow.self.signed", "false") \
            .option("es.net.http.auth.user", "elastic") \
            .option("es.net.http.auth.pass", "REDACTED") \
            .save()
```

We have successfully uploaded to ES with VMs and no SSL.  But in K8s we had to expose via Service LB, I setup a custom Service LB that only has data nodes accessible to use as an endpoint.  My guess is that it has to do with trying to load so much data (100's of GB) to ES with an LB in between now.  Any help would be greatly appreciated

**Comment by barkbay** [comment]
Thanks for reporting.

Even if I understand that now you have to use a load-balancer I just want to double check that the issue is related to ECK and not the environment: could you confirm that the hardware/jvm settings/storage or any setting that could have an impact on the performance are the same ?

**Comment by thbkrkr** [comment]
Closing for inactivity.
Please reopen if necessary. Thanks
