### ISSUE TITLE
Kibana pods crashing with FATAL Error

### ISSUE THREAD

**Issue by sarjeet2013** [elastic/cloud-on-k8s#1872]
## Proposal

**Use case. Why is this important?**
Kibana deployment is not stable and hence, not usable.

## Bug Report
**What did you do?**

**What did you expect to see?**
Kibana pods running with healthy status.

**What did you see instead? Under which circumstances?**
Kibana pod is crashing with FATAL Error. See the logs below.

* Logs:
```
{"type":"log","@timestamp":"2019-10-03T18:47:34Z","tags":["status","plugin:reporting@7.3.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [data] Elasticsearch cluster did not respond with license information.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-03T18:47:34Z","tags":["status","plugin:security@7.3.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - [data] Elasticsearch cluster did not respond with license information.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}

{"type":"log","@timestamp":"2019-10-03T18:48:01Z","tags":["reporting","warning"],"pid":1,"message":"Reporting plugin self-check failed. Please check the Kibana Reporting settings. Error: Request Timeout after 30000ms"}
{"type":"log","@timestamp":"2019-10-03T18:48:01Z","tags":["warning","task_manager"],"pid":1,"message":"PollError Request Timeout after 30000ms"}
{"type":"log","@timestamp":"2019-10-03T18:48:01Z","tags":["warning","maps"],"pid":1,"message":"Error scheduling telemetry task, received NotInitialized: Tasks cannot be scheduled until after task manager is initialized!"}
{"type":"log","@timestamp":"2019-10-03T18:48:01Z","tags":["warning","telemetry"],"pid":1,"message":"Error scheduling task, received NotInitialized: Tasks cannot be scheduled until after task manager is initialized!"}
{"type":"error","@timestamp":"2019-10-03T18:48:04Z","tags":["warning","process"],"pid":1,"level":"error","error":{"message":"Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:362:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:391:7)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:362:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:391:7)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n    at emitWarning (internal/process/promises.js:81:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:362:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:391:7)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
{"type":"error","@timestamp":"2019-10-03T18:48:04Z","tags":["warning","process"],"pid":1,"level":"error","error":{"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)","name":"UnhandledPromiseRejectionWarning","stack":"Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:362:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:391:7)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"},"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)"}
{"type":"log","@timestamp":"2019-10-03T18:48:31Z","tags":["fatal","root"],"pid":1,"message":"{ Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:362:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:391:7)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n  status: undefined,\n  displayName: 'RequestTimeout',\n  message: 'Request Timeout after 30000ms',\n  body: undefined,\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 503,\n     payload:\n      { statusCode: 503,\n        error: 'Service Unavailable',\n        message: 'Request Timeout after 30000ms' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/esUnavailable' }"}
{"type":"log","@timestamp":"2019-10-03T18:48:31Z","tags":["info","plugins-system"],"pid":1,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2019-10-03T18:48:31Z","tags":["info","plugins","translations"],"pid":1,"message":"Stopping plugin"}

 FATAL  Error: Request Timeout after 30000ms
```

There is already a ES 2 nodeGroups running fine with 1 count each.
```
➜ ~ kubectl get es
NAME       HEALTH   NODES   VERSION   PHASE   AGE
es-1node   green    2       7.3.0     Ready   19h
```

**Comment by sebgl** [comment]
Hey @sarjeet2013, could you copy the yaml spec of your Kibana resource?
Is it constantly failing? Or does it just happen randomly once in a while?

**Comment by sarjeet2013** [comment]
@sebgl This was consistently failing with same FATAL Error. I had to remove spec completely and redeployed it again, and didn't see this.

I'll update once this happen again, but wanted to know what the FATAL error was about, as it was same spec which was working earlier, and working now but happen to run into this on that specific deployment. I'll keep an eye on it if it happens again.

**Comment by charith-elastic** [comment]
Closing this for now. Please re-open with more details if you encounter the issue again.
