### ISSUE TITLE
ES cluster health unknown in E2E tests after a version upgrade

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2288]
```
=== RUN   TestVersionUpgradeSingle680To730/ES_cluster_health_should_eventually_be_green#01
Retries (5m0s timeout): ....................................................................................................
{"level":"error","@timestamp":"2019-12-18T02:18:13.088Z","message":"stopping early","ver":"0.0.0-00000000","error":"test failure","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/test/e2e/test.StepList.RunSequential\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/step.go:42\ngithub.com/elastic/cloud-on-k8s/test/e2e/test.RunMutations\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/run_mutation.go:37\ngithub.com/elastic/cloud-on-k8s/test/e2e/test.RunMutation\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/run_mutation.go:78\ngithub.com/elastic/cloud-on-k8s/test/e2e/es.RunESMutation\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/es/mutation_test.go:301\ngithub.com/elastic/cloud-on-k8s/test/e2e/es.TestVersionUpgradeSingle680To730\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/es/version_upgrade_test.go:34\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:909"}
    --- FAIL: TestVersionUpgradeSingle680To730/ES_cluster_health_should_eventually_be_green#01 (300.00s)
        utils.go:80: 
            	Error Trace:	utils.go:80
            	Error:      	Received unexpected error:
            	            	health is unknown
            	Test:       	TestVersionUpgradeSingle680To730/ES_cluster_health_should_eventually_be_green#01
```

From https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/125/testReport/junit/github/com_elastic_cloud-on-k8s_test_e2e_es/Run_tests_for_different_ELK_stack_versions_in_GKE___7_2_1___TestVersionUpgradeSingle680To730_ES_cluster_health_should_eventually_be_green_01/.

**Comment by sebgl** [comment]
I guess the cluster may not be reachable but looking at the operator logs I cannot see much.
https://github.com/elastic/cloud-on-k8s/pull/2290 and https://github.com/elastic/cloud-on-k8s/pull/2289 should help if that happens again.

**Comment by sebgl** [comment]
Ah, looking at the single Elasticsearch instance logs, this seems to be repeating continuously:

```
{"type": "server", "timestamp": "2019-12-18T02:18:17,214+0000", "level": "DEBUG", "component": "o.e.a.a.c.h.TransportClusterHealthAction", "cluster.name": "test-version-up-1-685-to-732-grq9", "node.name": "test-version-up-1-685-to-732-grq9-es-masterdata-0",  "message": "no known master node, scheduling a retry"  }
{"type": "server", "timestamp": "2019-12-18T02:18:20,539+0000", "level": "DEBUG", "component": "o.e.a.a.c.c.TransportClearVotingConfigExclusionsAction", "cluster.name": "test-version-up-1-685-to-732-grq9", "node.name": "test-version-up-1-685-to-732-grq9-es-masterdata-0",  "message": "timed out while retrying [cluster:admin/voting_config/clear_exclusions] after failure (timeout [30s])"  }
{"type": "server", "timestamp": "2019-12-18T02:18:20,539+0000", "level": "WARN", "component": "r.suppressed", "cluster.name": "test-version-up-1-685-to-732-grq9", "node.name": "test-version-up-1-685-to-732-grq9-es-masterdata-0",  "message": "path: /_cluster/voting_config_exclusions, params: {wait_for_removal=false}" , 
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.onTimeout(TransportMasterNodeAction.java:251) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) [elasticsearch-7.3.2.jar:7.3.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]"] }
```

**Comment by sebgl** [comment]
Closing this issue in favor of https://github.com/elastic/cloud-on-k8s/issues/2291 which really focuses on the actual bug.
