### ISSUE TITLE
AKS E2E jobs are broken 

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2913]
The last few builds failed with an HTTP error 400: https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-aks/

```
19:50:43  SSH key files '/root/.ssh/id_rsa' and '/root/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
19:51:01  --- Logging error ---
19:51:01  Traceback (most recent call last):
19:51:01    File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
19:51:01      cmd_result = self.invocation.execute(args)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
19:51:01      raise ex
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
19:51:01      results.append(self._run_job(expanded_arg, cmd_copy))
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
19:51:01      six.reraise(*sys.exc_info())
19:51:01    File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
19:51:01      raise value
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
19:51:01      result = cmd_copy(params)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
19:51:01      return self.handler(*args, **kwargs)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
19:51:01      return op(**command_args)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1919, in aks_create
19:51:01      raise ex
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1881, in aks_create
19:51:01      parameters=mc))
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerservice/v2020_03_01/operations/_managed_clusters_operations.py", line 665, in create_or_update
19:51:01      **operation_config
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerservice/v2020_03_01/operations/_managed_clusters_operations.py", line 616, in _create_or_update_initial
19:51:01      raise exp
19:51:01  msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/edd63b67-0ba2-4837-a4eb-cd484e9ff623/resourceGroups/cloudonk8s-dev/providers/Microsoft.ContainerService/managedClusters/jenkins-cloud-on-k8s-e2e-tests-aks-331?api-version=2020-03-01
19:51:01  
19:51:01  During handling of the above exception, another exception occurred:
19:51:01  
19:51:01  Traceback (most recent call last):
19:51:01    File "/opt/az/lib/python3.6/logging/__init__.py", line 994, in emit
19:51:01      stream.write(msg)
19:51:01  UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 883: ordinal not in range(128)
19:51:01  Call stack:
19:51:01    File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
19:51:01      "__main__", mod_spec)
19:51:01    File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
19:51:01      exec(code, run_globals)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
19:51:01      exit_code = cli_main(az_cli, sys.argv[1:])
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
19:51:01      return cli.invoke(args)
19:51:01    File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 227, in invoke
19:51:01      exit_code = self.exception_handler(ex)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 109, in exception_handler
19:51:01      return handle_exception(ex)
19:51:01    File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 55, in handle_exception
19:51:01      logger.error(ex.args[0])
19:51:01  Message: "Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service jenkins-cloud-on-k8s-e2e-tests-aks-331 in resource group cloudonk8s-dev failed. Message: Operation could not be completed as it results in exceeding approved standardDSv3Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: westeurope, Current Limit: 100, Current Usage: 96, Additional Required: 24, (Minimum) New Limit Required: 120. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22edd63b67-0ba2-4837-a4eb-cd484e9ff623%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the \u2018Details\u2019 section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests.. Details: "
19:51:01  Arguments: ()
19:51:01  Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service jenkins-cloud-on-k8s-e2e-tests-aks-331 in resource group cloudonk8s-dev failed. Message: Operation could not be completed as it results in exceeding approved standardDSv3Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: westeurope, Current Limit: 100, Current Usage: 96, Additional Required: 24, (Minimum) New Limit Required: 120. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22edd63b67-0ba2-4837-a4eb-cd484e9ff623%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the \u2018Details\u2019 section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests.. Details: 
19:51:01  Error: exit status 1
```

It seems to be a cpu quota issue.

**Comment by sebgl** [comment]
Some clusters were not properly cleaned up, probably due to https://github.com/elastic/cloud-on-k8s/issues/2898.

![image](https://user-images.githubusercontent.com/1050393/79753359-16027380-8316-11ea-8cd3-e5a96da75c19.png)

I'm deleting them manually.
