### ISSUE TITLE
Pods try to connect to outdated IP addresses

### ISSUE THREAD

**Issue by rgarcia89** [elastic/cloud-on-k8s#2919]
## Bug Report
**What did you do?**
On our DEV Cluster we do have an issue with the elastic-master and -data pods. It appears when resuming the cluster. As the DEV-Cluster runs in the cloud, we suspend the nodes between 9pm and 6am. After resuming the cluster the elastic pod stuck in Init:CrashLoopBackOff. From the logs I can see the following:

```
{"type": "server", "timestamp": "2020-04-20T19:02:57,005Z", "level": "WARN", "component": "o.e.c.NodeConnectionsService", "cluster.name": "elastic", "node.name": "elastic-es-master-2", "message": "failed to connect to {elastic-es-data-0}{IexIUptpS4Kzx7Kh80v6FA}{IahndnPWROiZHPz-2D9LgA}{10.101.2.156}{10.101.2.156:9300}{dil}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true} (tried [1] times)", "cluster.uuid": "vJDbksYdQoqxG-J2XIxFCg", "node.id": "FHyQizT9SZamutxckS0PIw" ,
"stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [elastic-es-data-0][10.101.2.156:9300] connect_exception",
"at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:989) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:162) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-7.6.2.jar:7.6.2]",
"at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]",
"at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]",
"at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]",
"at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]",
"at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:68) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:600) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]",
"at java.lang.Thread.run(Thread.java:830) [?:?]",
"Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 10.101.2.156/10.101.2.156:9300",
"Caused by: java.net.ConnectException: Connection refused",
"at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]",
"at sun.nio.ch.Net.pollConnectNow(Net.java:579) ~[?:?]",
"at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820) ~[?:?]",
"at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[?:?]",
"... 7 more"] }
{"type": "server", "timestamp": "2020-04-20T19:02:59,484Z", "level": "INFO", "component": "o.e.c.c.C.CoordinatorPublication", "cluster.name": "elastic", "node.name": "elastic-es-master-2", "message": "after [10s] publication of cluster state version [6238] is still waiting for {elastic-es-master-2}{FHyQizT9SZamutxckS0PIw}{NvLiTty3QcOomRec6sxL8w}{10.101.2.139}{10.101.2.139:9300}{lm}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20} [WAITING_FOR_QUORUM], {elastic-es-master-0}{6IFgl2JiTEiNV8xBWS58dA}{c_NSV9vqTdSHI5wmxWocPA}{10.101.7.217}{10.101.7.217:9300}{lm}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true} [SENT_PUBLISH_REQUEST], {elastic-es-data-1}{o75JrB8VQKaUEZqp3LXAcQ}{Q2Tf3OX8SNSLr8oeMYzQTA}{10.101.7.228}{10.101.7.228:9300}{dil}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true} [SENT_PUBLISH_REQUEST], {elastic-es-data-2}{xDI41chwSeGNsVMjMzUdBA}{jI4m4cZdQzqh8kqFdorrGg}{10.101.4.131}{10.101.4.131:9300}{dil}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true} [WAITING_FOR_QUORUM]", "cluster.uuid": "vJDbksYdQoqxG-J2XIxFCg", "node.id": "FHyQizT9SZamutxckS0PIw"  }
```

Here we see some IP addresses to which the elastic-es-master-2 is trying to connect.
However, these are outdated IP addresses, as the resuming process assigned new addresses to all pods:

```
pod/elastic-es-data-0                               1/1     Running                 0          37m     10.101.2.147   5-21-282-888-1-2338c778   <none>           <none>
pod/elastic-es-data-1                               1/1     Running                 0          37m     10.101.4.149   5-21-282-889-1-2338c785   <none>           <none>
pod/elastic-es-data-2                               1/1     Running                 0          37m     10.101.7.234   5-21-282-887-1-2338c741   <none>           <none>
pod/elastic-es-master-0                             1/1     Running                 0          37m     10.101.7.247   5-21-282-887-1-2338c741   <none>           <none>
pod/elastic-es-master-1                             1/1     Running                 0          37m     10.101.4.182   5-21-282-889-1-2338c785   <none>           <none>
pod/elastic-es-master-2                             0/1     Init:CrashLoopBackOff   22         22h     10.101.2.150   5-21-282-888-1-2338c778   <none>           <none>
pod/elastic-operator-0                              1/1     Running                 19         13d     10.101.7.206   5-21-282-887-1-2338c741   <none>           <none>
```

Deleting the pods manually will clear the issue, which of course is not a workout that can be used on long term.
Therefore, I would like to ask for help.

**What did you expect to see?**
I normally would expect that the correct IP address / or the IP address cache gets flush after every restart of the pod.

**What did you see instead? Under which circumstances?**
Already described above.

**Environment**

* ECK version: 1.0.1 (elastic and kibana 7.6.2)

* Kubernetes information: 1.17.4
	* Cloud: self managed on AWS
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rgarcia89** [comment]
fixed

**Comment by sebgl** [comment]
> fixed

@rgarcia89 can you provide more details on what was the cause of the problem and how you fixed it?

**Comment by rgarcia89** [comment]
The log got me confused.
It was not a real elasticsearch container issue, instead the init-container for the installation of plugins was again not working as described here https://github.com/elastic/elasticsearch/issues/55443 as I forgot to set `|| true` at the end of my condition, so a 1 was returned
