### ISSUE TITLE
Installation of plugins using initContainer stuck

### ISSUE THREAD

**Issue by bartversluijs** [elastic/cloud-on-k8s#3414]
## Bug Report
**What did you do?**
I was trying to install the `repository-s3` plugin using an initContainer.
I've tried to remove the initContainer and bash into the pod, and install it manually, but I got the same result.

**What did you expect to see?**
I was expecting to see an installation of the plugin and continue to start.

**What did you see instead? Under which circumstances?**
The `install-plugins` initContainer was stuck. It stays at Init:2/3.

**Environment**
Development

* ECK version:

	1.1.2

* Kubernetes information:

	DigitalOcean Managed Kubernetes (Version 1.18.3)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: vedicium
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: 1
    config:
      discovery.type: single-node

      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins # For backups
          command: ['sh', '-c', '/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3']
```

* Logs:
```
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%?? 
```

**Comment by thbkrkr** [comment]
Hi Bart,

You need to use the [`--batch` flag](https://www.elastic.co/guide/en/elasticsearch/plugins/current/_other_command_line_parameters.html#_batch_mode) as indicated in the ECK documentation to [install custom plugins](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-bundles-plugins.html):

```diff
-     command: ['sh', '-c', '/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3']
+     command: ['sh', '-c', '/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3']
```

This is because the `repository-s3` plugin asks the user for confirmation before continuing with the installation and it fails in the context of an init container without tty:
```sh
> kubectl logs vedicium-es-default-0 -c install-plugins 
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%?? 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
        at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:273)
        at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
        at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:67)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Comment by thbkrkr** [comment]
After fixing that, you will have another issue as `discovery.type: single-node` and `node.master: true` are exclusive. 
Just keep the latter `node.master: true` as `discovery.type` exists for a [specific usecase](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#single-node-discovery) and is useless in the context of ECK.

**Comment by jayceyzh** [comment]
![image](https://user-images.githubusercontent.com/31063321/222876813-b5873082-2a44-49a8-8348-66adb7eef89d.png)
![image](https://user-images.githubusercontent.com/31063321/222876817-ef92b1cf-b7bd-4207-9ced-43ac08ed2cf2.png)
Can someone help me look at this problem？

**Comment by thbkrkr** [comment]
> Can someone help me look at this problem？

Your YAML definition looks like a docker-compose configuration file, not a Kubernetes manifest. We try to keep GitHub issues only for actual bug reports and feature requests for the official Elastic operator. Please use the community forum [discuss](https://discuss.elastic.co/) for non ECK related questions like this.

Note that the equivalent of your definition in the ECK is:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: blurb
spec:
  version: 7.7.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.7.0/elasticsearch-analysis-ik-7.7.0.zip
```
