### ISSUE TITLE
TestTelemetry is flaky

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3709]
A runtime exception happened here: https://github.com/elastic/cloud-on-k8s/blob/ff40a5c3c3f92b1e9a10b5637b275a559413983a/test/e2e/kb/telemetry_test.go#L60, see logs from https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/225/consoleFull :

```
07:08:55  {"Time":"2020-09-04T05:08:54.819206327Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_be_able_to_connect_to_Elasticsearch","Output":"=== RUN   TestTelemetry/Kibana_should_be_able_to_connect_to_Elasticsearch\n"}
07:08:55  {"Time":"2020-09-04T05:08:54.903884762Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_be_able_to_connect_to_Elasticsearch","Output":"Retries (10m0s timeout): .\n"}
07:08:55  {"Time":"2020-09-04T05:08:54.903919376Z","Action":"run","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data"}
07:08:55  {"Time":"2020-09-04T05:08:54.903925122Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"=== RUN   TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427281488Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"Retries (10m0s timeout): .panic: runtime error: index out of range [0] with length 0\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427353421Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.42736221Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"goroutine 7295 [running]:\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427370898Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"github.com/elastic/cloud-on-k8s/test/e2e/kb.TestTelemetry.func1.1(0x1babaa0, 0xc000010018)\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427376749Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/kb/telemetry_test.go:60 +0x98a\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427381928Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"github.com/elastic/cloud-on-k8s/test/e2e/test.UntilSuccess.func1.1(0xc001439800, 0x1a68900)\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427387263Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:81 +0x8f\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427392326Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"github.com/elastic/cloud-on-k8s/pkg/utils/retry.UntilSuccess.func2(0xc0020a6120, 0xc000dc92e0)\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427403646Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"\t/go/src/github.com/elastic/cloud-on-k8s/pkg/utils/retry/retry.go:41 +0x27\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427409546Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"created by github.com/elastic/cloud-on-k8s/pkg/utils/retry.UntilSuccess\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.427414883Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Test":"TestTelemetry/Kibana_should_expose_eck_info_in_telemetry_data","Output":"\t/go/src/github.com/elastic/cloud-on-k8s/pkg/utils/retry/retry.go:40 +0xe5\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.431979073Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Output":"FAIL\tgithub.com/elastic/cloud-on-k8s/test/e2e/kb\t1318.482s\n"}
07:08:56  {"Time":"2020-09-04T05:08:56.43211018Z","Action":"fail","Package":"github.com/elastic/cloud-on-k8s/test/e2e/kb","Elapsed":1318.482}
07:08:56  {"log.level":"info","@timestamp":"2020-09-04T05:08:56.683Z","log.logger":"e2e-fx0oo","message":"Pod is in failed state","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","name":"eck-e2e-fx0oo-lnt7w"}
07:08:57  {"log.level":"info","@timestamp":"2020-09-04T05:08:57.485Z","log.logger":"e2e-fx0oo","message":"Log stream ended","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0"}
07:08:57  {"log.level":"info","@timestamp":"2020-09-04T05:08:57.485Z","log.logger":"e2e-fx0oo","message":"Log stream stopped","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0"}
```

**Comment by thbkrkr** [comment]
Running the test in a loop, I have not yet managed to reproduce it. 

I wonder if this could be due to a race condition as we have seen in the past (#2970), which only occurs when the Elastic stack starts.

I think we should fix `telemetry_test.go` by retrying until the length of the slice is not zero to avoid the panic. We will not hide a bug impacting ECK because we call the endpoint `/api/telemetry/v2/clusters/_stats` only to check that eck telemetry is working in this test. The telemetry reporting uses a completely different way (we publish a static file `telemetry.yml` using a secret).
