### ISSUE TITLE
TestUpdateESSecureSettings is failing

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3715]
Looks like `elastic-internal-init-keystore` [is not able to start](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-gke-k8s-versions/detail/cloud-on-k8s-e2e-tests-gke-k8s-versions/189/pipeline):

```json
 {
     "name": "elastic-internal-init-keystore",
     "state": {
         "waiting": {
             "reason": "CrashLoopBackOff",
             "message": "Back-off 5m0s restarting failed container=elastic-internal-init-keystore pod=test-es-keystore-lcj6-es-masterdata-0_e2e-khoqx-mercury(5f5947cc-e1a2-42cd-bcd6-7590a966736a)"
         }
     },
     "lastState": {
         "terminated": {
             "exitCode": 1,
             "reason": "Error",
             "startedAt": "2020-09-07T03:27:33Z",
             "finishedAt": "2020-09-07T03:27:36Z",
             "containerID": "docker://29d0d04aa46d68c1201feeabf3690e6e4383e353b80a1f7333227e422b233dbd"
         }
     },
     "ready": false,
     "restartCount": 10,
     "image": "docker.elastic.co/elasticsearch/elasticsearch:7.9.0",
     "imageID": "docker-pullable://docker.elastic.co/elasticsearch/elasticsearch@sha256:221c7f4a1ed3ed84ea7c1b28fd9fcb4c18e2d9370868da4b87cb78ba82f4d14e",
     "containerID": "docker://29d0d04aa46d68c1201feeabf3690e6e4383e353b80a1f7333227e422b233dbd"
 }
```

When running locally I have this error:

```
+ keystore_initialized_flag=/usr/share/elasticsearch/config/elastic-internal-init-keystore.ok
+ [[ -f /usr/share/elasticsearch/config/elastic-internal-init-keystore.ok ]]
+ echo 'Initializing keystore.'
+ /usr/share/elasticsearch/bin/elasticsearch-keystore create
Initializing keystore.
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'HEADLESS_SERVICE_NAME'
	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:116)
	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:69)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1165)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1121)
	at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:108)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:90)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:100)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:91)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:43)
```

**Comment by pebrc** [comment]
I think I broke that with the IPv6 PR. I did not run the full test suite before merging
