### ISSUE TITLE
OCP3 Jenkins job is broken

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4118]
```
10:36:32  fatal: [localhost]: FAILED! => {"changed": false, "msg": "GCP returned error: {u'error': {u'code': 400, u'message': u'Invalid value for field \\'resource.networkInterfaces[0]\\': \\'{  \"network\": \"https://www.googleapis.com/compute/v1/projects/****/global/networks/k8s-...\\'. Subnetwork should be specified for custom subnetmode network', u'errors': [{u'domain': u'global', u'message': u'Invalid value for field \\'resource.networkInterfaces[0]\\': \\'{  \"network\": \"https://www.googleapis.com/compute/v1/projects/****/global/networks/k8s-...\\'. Subnetwork should be specified for custom subnetmode network', u'reason': u'invalid'}]}}"}
```

**Comment by barkbay** [comment]
The original issue seems to be solved. [We are now hitting this one:](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp3/8/console)

```
15:00:59  panic: invalid patch format. version: 1.11.0+d4cacc0: strconv.Atoi: parsing "0+d4cacc0": invalid syntax
15:00:59  
15:00:59  goroutine 1 [running]:
15:00:59  github.com/elastic/cloud-on-k8s/pkg/controller/common/version.MustParse(...)
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/version/version.go:129
15:00:59  github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.getKubernetesVersion(0xc00023e600, 0x2, 0x2)
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/run/run.go:210 +0x3bc
15:00:59  github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.(*helper).initTestContext(0xc00023e600, 0x0, 0x0)
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/run/run.go:160 +0x1ca
15:00:59  github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.doRun(0xc0002d2780, 0x2, 0x2, 0x7ffdf61f3aa1, 0x2f, 0x7ffdf61f3b63, 0x5, 0x0, 0x0, 0x7ffdf61f3a5e, ...)
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/run/run.go:85 +0x262
15:00:59  github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.Command.func2(0xc0001cf600, 0xc0001d8d80, 0x0, 0x11, 0x0, 0x0)
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/run/command.go:72 +0xe5
15:00:59  github.com/spf13/cobra.(*Command).execute(0xc0001cf600, 0xc0001d8c60, 0x11, 0x12, 0xc0001cf600, 0xc0001d8c60)
15:00:59  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
15:00:59  github.com/spf13/cobra.(*Command).ExecuteC(0xc0001cf340, 0xc0006fbf68, 0x2, 0x2)
15:00:59  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
15:00:59  github.com/spf13/cobra.(*Command).Execute(...)
15:00:59  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
15:00:59  main.main()
15:00:59  	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/main.go:31 +0x11a
15:00:59  exit status 2
15:00:59  make: *** [Makefile:423: e2e-run] Error 1
15:01:02  Makefile:48: recipe for target 'ci-internal' failed
```

**Comment by pebrc** [comment]
We have https://github.com/elastic/cloud-on-k8s/issues/4119 for this. But I think it was not backported to all branches.

**Comment by thbkrkr** [comment]
Closing as the OCP3 Jenkins Job is working fine (OCP env is created and the tests are executed).
The last run of the job failed because the test `agent.TestSystemIntegrationConfig` was not passed. 
I will use #4119 to continue debugging this test failure.
