### ISSUE TITLE
E2E getKubernetesVersion cannot deal with OCP3 patch versions

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4119]
```
{"log.level":"info","@timestamp":"2021-01-14T10:56:21.396+0100","log.logger":"e2e-lkzoz","message":"Cleaning up the scratch directory","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","directory":"/tmp/eck-e2e/e2e-lkzoz"}
panic: invalid patch format. version: 1.11.0+d4cacc0: strconv.Atoi: parsing "0+d4cacc0": invalid syntax

goroutine 1 [running]:
github.com/elastic/cloud-on-k8s/pkg/controller/common/version.MustParse(...)
	/Users/pebrc/src/cloud-on-k8s/pkg/controller/common/version/version.go:129
github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.getKubernetesVersion(0xc0002e8000, 0x2, 0x2)
	/Users/pebrc/src/cloud-on-k8s/test/e2e/cmd/run/run.go:209 +0x3a7
github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.(*helper).initTestContext(0xc0002e8000, 0x0, 0x0)
	/Users/pebrc/src/cloud-on-k8s/test/e2e/cmd/run/run.go:160 +0x1cd
github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.doRun(0xc000351640, 0x2, 0x2, 0x7ffeefbff631, 0x30, 0x7ffeefbff6b7, 0x6, 0x0, 0x0, 0x7ffeefbff5ee, ...)
	/Users/pebrc/src/cloud-on-k8s/test/e2e/cmd/run/run.go:85 +0x25d
github.com/elastic/cloud-on-k8s/test/e2e/cmd/run.Command.func2(0xc0001c1340, 0xc0004dc700, 0x0, 0x10, 0x0, 0x0)
	/Users/pebrc/src/cloud-on-k8s/test/e2e/cmd/run/command.go:71 +0xc4
github.com/spf13/cobra.(*Command).execute(0xc0001c1340, 0xc0004dc600, 0x10, 0x10, 0xc0001c1340, 0xc0004dc600)
	/Users/pebrc/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c1080, 0xc0004bff68, 0x2, 0x2)
	/Users/pebrc/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pebrc/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/Users/pebrc/src/cloud-on-k8s/test/e2e/cmd/main.go:31 +0x118
exit status 2
```

It looks like OCP3 has some slightly idiosyncratic patch version format. `1.11.0+d4cacc0` 

`semver.ParseTolerant()` should work instead or we add a tolerant mode to our versioning code.

**Comment by david-kow** [comment]
`semver.ParseTolerant()` should work. Having said that, the plus sign is in the [spec](https://semver.org/#spec-item-10).
