### ISSUE TITLE
TestVersionUpgradeAndRespecToLatest7x is failing

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4383]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-stack-versions/379/gcsObjects/

Two out of three Kibana instances came up successfully. One got stuck with 
```
{"type":"log","@timestamp":"2021-03-25T04:13:57+00:00","tags":["info","savedobjects-service"],"pid":6,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2021-03-25T04:13:57+00:00","tags":["info","savedobjects-service"],"pid":6,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["info","savedobjects-service"],"pid":6,"message":"Creating index .kibana_task_manager_1."}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["info","savedobjects-service"],"pid":6,"message":"Removing index templates: kibana_index_template:.kibana"}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["warning","savedobjects-service"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: resource_already_exists_exception"}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["warning","savedobjects-service"],"pid":6,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_task_manager_1 and restarting Kibana."}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["warning","savedobjects-service"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: index_template_missing_exception"}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["fatal","root"],"pid":6,"message":"ResponseError: index_template_missing_exception\n    at onBody (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:333:23)\n    at IncomingMessage.onEnd (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21) {\n  meta: {\n    body: { error: [Object], status: 404 },\n    statusCode: 404,\n    headers: {\n      'content-type': 'application/json; charset=UTF-8',\n      'content-length': '257'\n    },\n    meta: {\n      context: null,\n      request: [Object],\n      name: 'elasticsearch-js',\n      connection: [Object],\n      attempts: 0,\n      aborted: false\n    }\n  }\n}"}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2021-03-25T04:13:58+00:00","tags":["info","plugins","monitoring","monitoring","kibana-monitoring"],"pid":6,"message":"Monitoring stats collection is stopped"}
{"type":"log","@timestamp":"2021-03-25T04:14:27+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:14:57+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:15:27+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:15:57+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:16:27+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:16:57+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
{"type":"log","@timestamp":"2021-03-25T04:17:27+00:00","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: Cluster client cannot be used after it has been closed. error"}
```

This seem like a Kibana bug in that the coordination between multiple instances did not seem to resolve to a working state. Even if one instance does the saved object migration the others should be able to recover once it completes. If further investigation shows this to be case we should raise it against the Kibana repo as an issue. 

I also wonder if we should implement the recommendation from https://www.elastic.co/guide/en/kibana/7.x/upgrade-migrations.html#_upgrading_multiple_kibana_instances_2

>For large deployments with more than 10 Kibana instances and more than 10 000 saved objects, the upgrade downtime can be reduced by bringing up a single Kibana instance and waiting for it to complete the upgrade migration before bringing up the remaining instances.

**Comment by thbkrkr** [comment]
Additional cleaned logs from the 3 instances, which highlight the concurrency to perform the migration:
```
[4z672]  57+00:00  info  savedobjects-service  Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
[4z672]  57+00:00  info  savedobjects-service  Starting saved objects migrations
[4z672]  58+00:00  info  savedobjects-service  Creating index .kibana_task_manager_1.
[4z672]  58+00:00  info  savedobjects-service  Removing index templates: kibana_index_template:.kibana
[4z672]  58+00:00  info  savedobjects-service  Creating index .kibana_2.
[4z672]  58+00:00  info  savedobjects-service  Pointing alias .kibana_task_manager to .kibana_task_manager_1.
[4z672]  58+00:00  info  savedobjects-service  Finished in 255ms.
[4z672]  58+00:00  info  savedobjects-service  Migrating .kibana_1 saved objects to .kibana_2
[4z672]  58+00:00  info  savedobjects-service  Pointing alias .kibana to .kibana_2.
[4z672]  58+00:00  info  savedobjects-service  Finished in 569ms.
[4z672]  59+00:00  info  listening             Server running at https://0.0.0.0:5601                                    

[wmdjf]  58+00:00  info  savedobjects-service  Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
[wmdjf]  58+00:00  info  savedobjects-service  Starting saved objects migrations
[wmdjf]  58+00:00  info  savedobjects-service  Creating index .kibana_task_manager_1.
[wmdjf]  58+00:00  info  savedobjects-service  Creating index .kibana_2.
[wmdjf]  58+00:00  warn  savedobjects-service  Unable to connect to Elasticsearch. Error: resource_already_exists_exception
[wmdjf]  58+00:00  warn  savedobjects-service  Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_task_manager_1 and restarting Kibana.
[wmdjf]  58+00:00  warn  savedobjects-service  Unable to connect to Elasticsearch. Error: resource_already_exists_exception
[wmdjf]  58+00:00  warn  savedobjects-service  Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_2 and restarting Kibana.
[wmdjf]  01+00:00  info  listening             Server running at https://0.0.0.0:5601

[7sk9q]  57+00:00  info  savedobjects-service  Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
[7sk9q]  57+00:00  info  savedobjects-service  Starting saved objects migrations
[7sk9q]  58+00:00  info  savedobjects-service  Creating index .kibana_task_manager_1.
[7sk9q]  58+00:00  info  savedobjects-service  Removing index templates: kibana_index_template:.kibana
[7sk9q]  58+00:00  warn  savedobjects-service  Unable to connect to Elasticsearch. Error: resource_already_exists_exception
[7sk9q]  58+00:00  warn  savedobjects-service  Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_task_manager_1 and restarting Kibana.
[7sk9q]  58+00:00  warn  savedobjects-service  Unable to connect to Elasticsearch. Error: index_template_missing_exception
[7sk9q]  58+00:00  fatal root                  ResponseError: index_template_missing_exception
```

**Comment by thbkrkr** [comment]
Looks like it was a flakyness, closing because it never happened again.
