### ISSUE TITLE
ES pods error out with java.nio.file.AccessDeniedException 

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [elastic/cloud-on-k8s#4580]
## Bug Report
**What did you do?**

Deployed ECK and tried to create Elasticsearch resource.

**What did you expect to see?**

Elasticsearch pods running and a healthy cluster

**What did you see instead? Under which circumstances?**

We are using the following custom image

```
ARG elasticsearch_version="7.12.1"
FROM docker.elastic.co/elasticsearch/elasticsearch:${elasticsearch_version}
RUN bin/elasticsearch-plugin install --batch repository-gcs
RUN bin/elasticsearch-plugin install --batch repository-s3
```

Elasticsearch resource pods in `Error/CrashLoopBackOff` and the following exception in their logs

```
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:79)
	at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:209)
	at org.elasticsearch.common.settings.HasPasswordKeyStoreCommand.execute(HasPasswordKeyStoreCommand.java:31)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
```

**Environment**

* ECK version:

	`1.5.0+8091c0da`

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:

	* Cloud: GKE
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

(ommitting managedFields)

```
$ kubectl get es -o yaml

apiVersion: v1
items:
- apiVersion: elasticsearch.k8s.elastic.co/v1
  kind: Elasticsearch
  metadata:
    annotations:
      common.k8s.elastic.co/controller-version: 1.5.0
      elasticsearch.k8s.elastic.co/initial-master-nodes: mycluster-es-multirolenodes1-0,mycluster-es-multirolenodes1-1,mycluster-es-multirolenodes1-2
      helm.fluxcd.io/antecedent: elastic:helmrelease/elastic-stack
    creationTimestamp: "2021-06-17T19:54:35Z"
    generation: 2
    managedFields:
    name: mycluster
    namespace: elastic
    resourceVersion: "507681408"
    selfLink: /apis/elasticsearch.k8s.elastic.co/v1/namespaces/elastic/elasticsearches/mycluster
    uid: ceeb3c2b-e14e-4760-a1e0-3c58266fcadb
  spec:
    auth: {}
    http:
      service:
        metadata:
          creationTimestamp: null
        spec: {}
      tls:
        certificate: {}
        selfSignedCertificate:
          disabled: true
    nodeSets:
    - config:
        node.roles:
        - master
        - ingest
        - data
        - remote_cluster_client
        - ml
        node.store.allow_mmap: "false"
      count: 3
      name: multirolenodes1
      podTemplate:
        metadata:
          annotations:
            ad.datadoghq.com/elasticsearch.check_names: '["elastic"]'
            ad.datadoghq.com/elasticsearch.init_configs: '[{}]'
            ad.datadoghq.com/elasticsearch.instances: |
              [
                {
                  "url": "http://%%host%%:9200"
                }
              ]
            ad.datadoghq.com/elasticsearch.logs: '[{"source":"elasticsearch","service":"mycluster-es-http"}]'
            traffic.sidecar.istio.io/excludeInboundPorts: "9300"
            traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
            traffic.sidecar.istio.io/includeInboundPorts: '*'
          creationTimestamp: null
          labels:
            app: elasticsearch
        spec:
          containers:
          - env:
            - name: VARIABLE
              value: VALUE
            envFrom:
            - secretRef:
                name: elastic-stack
            image: gcr.io/repo/elasticsearch-eck:7.12.1
            name: elasticsearch
            resources:
              limits:
                cpu: "2"
                memory: 6Gi
              requests:
                cpu: 500m
                memory: 2Gi
      volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: standard-rwo
        status: {}
    secureSettings:
    - entries:
      - key: gcs.client.default.credentials_file
      secretName: elastic-stack
    transport:
      service:
        metadata:
          creationTimestamp: null
        spec: {}
      tls:
        certificate: {}
    updateStrategy:
      changeBudget: {}
    version: 7.12.1
    volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion
  status:
    health: unknown
    phase: ApplyingChanges
    version: 7.12.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

* Logs:

Apparently no error in operator pod logs.

```
elastic-operator-0 manager {"log.level":"info","@timestamp":"2021-06-18T06:56:22.901Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"1.5.0+8091c0da","service.type":"eck","ecs.version":"1.4.0","kind":"ConfigMap","namespace":"elastic-system","name":"elastic-licensing"}
elastic-operator-0 manager {"log.level":"info","@timestamp":"2021-06-18T06:56:30.034Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.5.0+8091c0da","service.type":"eck","ecs.version":"1.4.0","iteration":5448,"namespace":"elastic","es_name":"mycluster"}
elastic-operator-0 manager {"log.level":"info","@timestamp":"2021-06-18T06:56:30.321Z","log.logger":"driver","message":"ES cannot be reached yet, re-queuing","service.version":"1.5.0+8091c0da","service.type":"eck","ecs.version":"1.4.0","namespace":"elastic","es_name":"mycluster"}
elastic-operator-0 manager {"log.level":"info","@timestamp":"2021-06-18T06:56:30.321Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.5.0+8091c0da","service.type":"eck","ecs.version":"1.4.0","iteration":5448,"namespace":"elastic","es_name":"mycluster","took":0.2870281
```

**Comment by pantelis-karamolegkos** [comment]
OK this turns out to be really funny (...and perhaps one of the most misleading errors I have ever come across).

The issue was that the `json` used to set the secret of the GCP service account was malformed, i.e. the closing bracket was missing.

```
{
  "type": "service_account",
  "project_id": "XXXXXXXX",
  "private_key_id": "XXXXXXXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\nXXXXXXXXXXXXXXXXXXX=\n-----END PRIVATE KEY-----\n",
  "client_email": "nXXXXXXXXXXXXXXXXXXX1.iam.gserviceaccount.com",
  "client_id": "nXXXXXXXXXXXXXXXXXXX",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "XXXXXXXX"
```

I don't know how is this possible to cause the `AccessDenied` error and / or if it the feedback I am providing is worth

(the fact of the matter is that I lost several hours struggling with `fsGroups`, `securityContext`, capabilities and other stuff that turned out to be unrelated...
