### ISSUE TITLE
how do I configure "elasticsearch.ssl.certificateAuthorities" in Kibana and etc for ECK?

### ISSUE THREAD

**Issue by pabloandrei** [elastic/cloud-on-k8s#5173]
After up the ECK, the certificate is not valid for accessing KIBANA via HTTPS.
Question, how does the pod need to have the certificate, and CDRS + Operator creates the certificates in SECRETs? how do i configure usage?

**YAML:**
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: kibana
spec:
  version: 7.16.0
  count: 1
  config:
    elasticsearch.ssl.certificateAuthorities:
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-http-certs-internal
        key: ca.crt
  elasticsearchRef:
    name: elasticsearch
```
IS CORRET????

**SECRET:**
![image](https://user-images.githubusercontent.com/16004192/146227022-1aeee218-eef3-425e-86fa-e2513bc21a16.png)

* ECK version: 1.9.0

* Kubernetes information: Microk8s

* Logs:
```
2021-12-15T13:37:32-03:00 {"type":"log","@timestamp":"2021-12-15T16:37:32+00:00","tags":["fatal","root"],"pid":8,"message":"CriticalError: Unknown configuration key(s): \"valueFrom.secretKeyRef.key\", \"valueFrom.secretKeyRef.name\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/kibana/src/core/server/config/ensure_valid_configuration.js:35:11)\n    at Server.preboot (/usr/share/kibana/src/core/server/server.js:166:5)\n    at Root.preboot (/usr/share/kibana/src/core/server/root/index.js:48:14)\n    at bootstrap (/usr/share/kibana/src/core/server/bootstrap.js:99:9)\n    at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:229:5) {\n  code: 'InvalidConfig',\n  processExitCode: 64,\n  cause: undefined\n}"}
2021-12-15T13:37:32-03:00 
2021-12-15T13:37:32-03:00  FATAL  Error: Unknown configuration key(s): "valueFrom.secretKeyRef.key", "valueFrom.secretKeyRef.name". Check for spelling errors and ensure that expected plugins are installed.
```

![image](https://user-images.githubusercontent.com/16004192/146226666-6b1946cf-94f5-49e2-9e45-1881a4198b41.png)

**Comment by pebrc** [comment]
By default the operator issues self signed certificates. You do not have to configure anything but a Webbrowser will not trust them See the documentation on how configure your own certificates or trust the self-signed ones if you are just experimenting https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-tls-certificates.html

Also please move this discussion to our [community forum](https://discuss.elastic.co/c/orchestration/eck/79) and use GitHub only for bug reports or feature requests, thank you!

**Comment by pabloandrei** [comment]
> By default the operator issues self signed certificates. You do not have to configure anything but a Webbrowser will not trust them See the documentation on how configure your own certificates or trust the self-signed ones if you are just experimenting https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-tls-certificates.html
> 
> Also please move this discussion to our [community forum](https://discuss.elastic.co/c/orchestration/eck/79) and use GitHub only for bug reports or feature requests, thank you!

@pebrc tks for your support. To end.. Suppose I have a valid certificate, to work for a specific DNS, for this scenario, should I then change the value of Secrets *-tls (ca.crt, tls.crt and tls.key) created by the operator manually on K8s?
Example: 
![image](https://user-images.githubusercontent.com/16004192/146270701-8afea6ac-9f6d-4ce1-8e58-2d805cfd5967.png)
