### ISSUE TITLE
securityContext in podTemplate section is being ignored?

### ISSUE THREAD

**Issue by perezjasonr** [elastic/cloud-on-k8s#5446]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

used the securityContext field in podTemplate section, particularly fsGroup

**What did you expect to see?**

fsGroup that I assigned

**What did you see instead? Under which circumstances?**

it seems to be 1337, even though i put 1000

**Environment**

* ECK version:

	1.9.1, with es image 7.16.2

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	AWS, self managed (kubeadm 1.20.4 and 1.22.2)
	
```
$ kubectl version
```

* Resource definition:
```
see below
```

* Logs:

i dont see anything in particular in the logs from the operator but this shows up (relevant permission error when doing plugin install). This used to not happen:

```
-> Installing file:///usr/share/elasticsearch/repository-s3-7.16.2.zip
-> Downloading file:///usr/share/elasticsearch/repository-s3-7.16.2.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See https://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Failed installing file:///usr/share/elasticsearch/repository-s3-7.16.2.zip
-> Rolling back file:///usr/share/elasticsearch/repository-s3-7.16.2.zip
Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/repository-s3: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setOwners(UnixFileAttributeViews.java:291)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setOwner(UnixFileAttributeViews.java:313)
	at org.elasticsearch.plugins.cli.InstallPluginAction.setOwnerGroup(InstallPluginAction.java:1037)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installConfig(InstallPluginAction.java:1011)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPluginSupportFiles(InstallPluginAction.java:934)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:908)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:245)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:88)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.plugins.cli.PluginCli.main(PluginCli.java:36)
-> Rolled back file:///usr/share/elasticsearch/repository-s3-7.16.2.zip
```

i posted in 
https://github.com/elastic/cloud-on-k8s/issues/4781
but making a new issue for it just in case i found something.

Hello, I just wanted to make you all aware I followed this documentation (thank you for this btw), but it seems the operator is ignoring it.

heres my pod template section:

```
podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/includeInboundPorts: '*'
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
            value: "5"
          - name: ES_JAVA_OPTS
            value: -Dlog4j2.formatMsgNoLookups=true
          name: elasticsearch
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
        securityContext:
          fsGroup: 1000
```

this is live, and accepted by the operator. However, the actual elasticsearch pod has:

```
  securityContext:
    fsGroup: 1337
```

i cannot recall now, but i think this used to work...the last change we made was the jump to 7.16.2 image due to the log4j vuln...not sure if its possible a newer version may have caused a regression here. I dont recall this being ignored/overwritten by the operator in the past.

as stated above, this is problematic because we indeed use an image that doesn't run as root, i believe this is breaking a plugin install via init container were doing that used to work.

let me know if i should open a new issue for it, wasn't sure if i just understood this wrong and didnt want a whole new issue over it.

**Comment by thbkrkr** [comment]
I don't reproduce. Could you test with the example below?

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: scfsg
spec:
  version: 7.16.2
  nodeSets:
  - name: master
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/includeInboundPorts: '*'
      spec:
        containers:
        - env:
          - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
            value: "5"
          - name: ES_JAVA_OPTS
            value: -Dlog4j2.formatMsgNoLookups=true
          name: elasticsearch
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
        securityContext:
          fsGroup: 1013
```

```
> k get po scfsg-es-master-0  -o json | jq '.spec.securityContext.fsGroup'
1013

> k exec sc-es-master-0 -- id elasticsearch
uid=1000(elasticsearch) gid=1000(elasticsearch) groups=1000(elasticsearch),0(root)

> k exec scfsg-es-master-0 -- ls -n config/elasticsearch.keystore
-rw-rw---- 1 1000 1013 199 Mar  8 10:22 config/elasticsearch.keystore
```

**Comment by perezjasonr** [comment]
So far I can't see how your example differs from mine other than the fsgroup being 1013 instead of 1000 in my case, but I will try it now and let you know.

**Comment by perezjasonr** [comment]
sorry about the delay, i ended up having other issues and had to troubleshoot to get back to where I was.

I used your exact manifest, but in elastic-system ns, here is the live object:


```
kubectl get es -n elastic-system scfsg -o yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    common.k8s.elastic.co/controller-version: 1.9.1
    elasticsearch.k8s.elastic.co/cluster-uuid: _F1vgfx6Q9a53C8OQhIIRg
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"elasticsearch.k8s.elastic.co/v1","kind":"Elasticsearch","metadata":{"annotations":{},"name":"scfsg","namespace":"elastic-system"},"spec":{"nodeSets":[{"config":{"node.store.allow_mmap":false},"count":1,"name":"master","podTemplate":{"metadata":{"annotations":{"traffic.sidecar.istio.io/excludeInboundPorts":"9300","traffic.sidecar.istio.io/excludeOutboundPorts":"9300","traffic.sidecar.istio.io/includeInboundPorts":"*"}},"spec":{"containers":[{"env":[{"name":"PRE_STOP_ADDITIONAL_WAIT_SECONDS","value":"5"},{"name":"ES_JAVA_OPTS","value":"-Dlog4j2.formatMsgNoLookups=true"}],"name":"elasticsearch","resources":{"requests":{"cpu":"300m","memory":"256Mi"}}}],"securityContext":{"fsGroup":1013}}}}],"version":"7.16.2"}}
  creationTimestamp: "2022-03-14T20:33:27Z"
  generation: 2
  name: scfsg
  namespace: elastic-system
  resourceVersion: "51552"
  uid: f8b76af4-b385-4d68-ad81-a25773df4712
spec:
  auth: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  monitoring:
    logs: {}
    metrics: {}
  nodeSets:
  - config:
      node.store.allow_mmap: false
    count: 1
    name: master
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/includeInboundPorts: '*'
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
            value: "5"
          - name: ES_JAVA_OPTS
            value: -Dlog4j2.formatMsgNoLookups=true
          name: elasticsearch
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
        securityContext:
          fsGroup: 1013
  transport:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  updateStrategy:
    changeBudget: {}
  version: 7.16.2
status:
  availableNodes: 1
  health: green
  phase: Ready
  version: 7.16.2
```

then:

```
kubectl get pod scfsg-es-master-0 -n elastic-system -o jsonpath='{.spec.securityContext}'
{"fsGroup":1337}
```

so this is consistent with my normal deployment. why is yours respecting the sec context and mine isn't? even if I use the es object you provided, only thing i can imagine is my operator is the differing factor, Is there something in the operator we need to look at perhaps??

**Comment by perezjasonr** [comment]
@thbkrkr what version of operator did you use? did you match 1.9.1?

**Comment by barkbay** [comment]
Could istio change this setting ? See https://github.com/istio/istio/issues/26882

**Comment by perezjasonr** [comment]
very interesting, you might have found the reason. I'll test it right now and take istio out of the equation. if it goes back to the proper fsgroup we know the culprit.

it also might be something to add to the eck operator docs because the docs do go over adding istio, and setting securitycontext (ie fsgroup) separately, it might be noteworthy to point out those two dont get along.

**Comment by perezjasonr** [comment]
Removing istio from the picture did indeed resolve the issue. So I think we have isolated it.

I'm not sure how best to reconcile keeping istio while at the same time not having elasticsearch run as root. In the case of my plugin install, i could just force it to runAs 1337, then add in a chown after its done to make it elasticsearch:0 or 1000:0? I guess i can give that a try

**Comment by perezjasonr** [comment]
just wanted to let you guys know that the same solution in the issue that barkbay referenced also worked for me. Essentially, the fsgroup override from istio is a "legacy" feature, which defaults to true, it can be disabled. I did that and now I can have istio with my eck operator setup while still having fsgroup set so that I can run es as non root. I think this might be a big deal soon with es 8 not running as root. Hope that helps. I'm gonna close this for now, but just wanted to say it might be worth a mention in the eck operator docs either under the istio/service mesh options and/or securityContext section.
