### ISSUE TITLE
Elasticsearch using ECK: failed to start again after Elasticsearch resources were removed from cluster

### ISSUE THREAD

**Issue by lui2131** [elastic/cloud-on-k8s#5543]
## Bug Report

**What did you do?**
Trying to add another node to the AKS (kubernetes) cluster caused the health of the Elasticsearch cluster to fail (related to networking problems and not necessarily elastic's fault) .  While troubleshooting I ended up deleting the StatefulSet and then the manifest of type "Elasticsearch" to remove the running Elasticsearch StatefulSet pods and try to restart the whole cluster.  After deleting the pods the PersistentVolumes and PersistentVolumeClaims remained behind due to the ` volumeClaimDeletePolicy: DeleteOnScaledownOnly` policy.   I then reapplied the same manifest of type "Elasticsearch" to the cluster.

**What did you expect to see?**
I expected the Elasticsearch cluster instance to start running with the same PersistentVolumes that had been used prior, thus preserving my data.

**What did you see instead? Under which circumstances?**
The Elasticsearch cluster failed to start up correctly.
```shell
$ kc get Elasticsearch
NAME            HEALTH    NODES   VERSION   PHASE             AGE
elasticsearch   unknown   1       7.15.0    ApplyingChanges   4h25m
```
```shell
kc get pods
NAME                               READY   STATUS             RESTARTS   AGE
elasticsearch-es-default-0         0/1     CrashLoopBackOff   30         168m
elasticsearch-es-default-1         1/1     Running            1          167m
elasticsearch-es-default-2         0/1     CrashLoopBackOff   30         168m
```
More information such as relevant logs are included below in the log section.

**Environment**
(Exposing Elasticsearch cluster to internal network using Azure Load Balancer)

* ECK version:
	 * docker.elastic.co/eck/eck-operator:1.8.0

* Kubernetes information:
	* Cloud: AKS - version 1.20.9

* Elasticsearch version:
	* docker.elastic.co/elasticsearch/elasticsearch:7.15.0

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

* Resource definition:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  version: 7.15.0
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: default
      count: 3
      config:
        # currently no need for ingest node(s) since we are not doing any data processing with ingest
        node.roles: ["master", "data"]
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.exporters.my_local:
          type: local
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Gi
            storageClassName: azure-storage
      podTemplate:
        metadata:
          labels:
            elastic-pod-label: "elasticsearch"
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms2g -Xmx2g
              resources:
                requests:
                  memory: 4Gi
                  cpu: 0.5
                limits:
                  memory: 4Gi
          affinity:
            # Hard requirement for elasticsearch pods to be scheduled on a different node
            # from other elasticsearch pods
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: elastic-pod-label
                        operator: In
                        values:
                        - elasticsearch
                  topologyKey: topology.kubernetes.io/zone
  http:
    service:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
        ports:
          - name: https
            protocol: TCP
            port: 443
            targetPort: 9200 #9200 required as targetPort
          - name: default
            protocol: TCP
            port: 9200
            targetPort: 9200 #9200 required as targetPort
```

* Logs:
Relevant elasticsearch-es-default-1 (pod) logs 
```json
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:46,769Z",
  "level": "WARN",
  "component": "r.suppressed",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "path: /_cluster/settings, params: {}",
  "stacktrace": [
    "org.elasticsearch.discovery.MasterNotDiscoveredException: null",
    "at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:234) [elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:324) [elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:241) [elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:591) [elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.15.0.jar:7.15.0]",
    "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
    "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
    "at java.lang.Thread.run(Thread.java:831) [?:?]"
  ]
}
```
```json
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9302], node [null], requesting [false] connection failed: [][127.0.0.1:9302] connect_exception: Connection refused: /127.0.0.1:9302: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9304], node [null], requesting [false] connection failed: [][[::1]:9304] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9304: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9305], node [null], requesting [false] connection failed: [][[::1]:9305] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9305: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9303], node [null], requesting [false] connection failed: [][127.0.0.1:9303] connect_exception: Connection refused: /127.0.0.1:9303: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9301], node [null], requesting [false] connection failed: [][[::1]:9301] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9301: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,055Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9303], node [null], requesting [false] connection failed: [][[::1]:9303] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9303: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,055Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9304], node [null], requesting [false] connection failed: [][127.0.0.1:9304] connect_exception: Connection refused: /127.0.0.1:9304: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,057Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9305], node [null], requesting [false] connection failed: [][127.0.0.1:9305] connect_exception: Connection refused: /127.0.0.1:9305: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,057Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9302], node [null], requesting [false] connection failed: [][[::1]:9302] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9302: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,057Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9301], node [null], requesting [false] connection failed: [][127.0.0.1:9301] connect_exception: Connection refused: /127.0.0.1:9301: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,073Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9300], node [null], requesting [false] connection failed: [elasticsearch-es-default-1][10.125.7.21:9300] local node found"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:47,073Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9300], node [null], requesting [false] connection failed: [elasticsearch-es-default-1][10.125.7.21:9300] local node found"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:48,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [127.0.0.1:9302], node [null], requesting [false] connection failed: [][127.0.0.1:9302] connect_exception: Connection refused: /127.0.0.1:9302: Connection refused"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:34:48,053Z",
  "level": "WARN",
  "component": "o.e.d.PeerFinder",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-1",
  "message": "address [[::1]:9305], node [null], requesting [false] connection failed: [][[::1]:9305] connect_exception: Connection refused: /[0:0:0:0:0:0:0:1]:9305: Connection refused"
}
```

Relevant elasticsearch-es-default-0 (pod) logs
```json
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,364Z",
  "level": "ERROR",
  "component": "o.e.b.ElasticsearchUncaughtExceptionHandler",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "uncaught exception in thread [main]",
  "stacktrace": [
    "org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to resolve publish address]; nested: UnknownHostException[elasticsearch-es-default-0.elasticsearch-es-default.elastic.svc: Name or service not known];",
    "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:171) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:158) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114) ~[elasticsearch-cli-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:123) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "Caused by: org.elasticsearch.transport.BindTransportException: Failed to resolve publish address",
    "at org.elasticsearch.http.AbstractHttpServerTransport.bindServer(AbstractHttpServerTransport.java:164) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:231) ~[?:?]",
    "at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport.doStart(SecurityNetty4HttpServerTransport.java:67) ~[?:?]",
    "at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.node.Node.start(Node.java:987) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:313) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:408) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "... 6 more",
    "Caused by: java.net.UnknownHostException: elasticsearch-es-default-0.elasticsearch-es-default.elastic.svc: Name or service not known",
    "at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]",
    "at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]",
    "at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]",
    "at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]",
    "at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]",
    "at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]",
    "at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]",
    "at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:237) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:143) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.http.AbstractHttpServerTransport.bindServer(AbstractHttpServerTransport.java:162) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:231) ~[?:?]",
    "at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport.doStart(SecurityNetty4HttpServerTransport.java:67) ~[?:?]",
    "at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.node.Node.start(Node.java:987) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:313) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:408) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167) ~[elasticsearch-7.15.0.jar:7.15.0]",
    "... 6 more"
  ]
}
uncaught exception in thread [main]
BindTransportException[Failed to resolve publish address]; nested: UnknownHostException[elasticsearch-es-default-0.elasticsearch-es-default.elastic.svc: Name or service not known];
Likely root cause: java.net.UnknownHostException: elasticsearch-es-default-0.elasticsearch-es-default.elastic.svc: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:237)
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187)
	at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:143)
	at org.elasticsearch.http.AbstractHttpServerTransport.bindServer(AbstractHttpServerTransport.java:162)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:231)
	at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport.doStart(SecurityNetty4HttpServerTransport.java:67)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
	at org.elasticsearch.node.Node.start(Node.java:987)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:313)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:408)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:158)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:123)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,373Z",
  "level": "INFO",
  "component": "o.e.n.Node",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "stopping ..."
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,374Z",
  "level": "INFO",
  "component": "o.e.x.w.WatcherService",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "stopping watch service, reason [shutdown initiated]"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,375Z",
  "level": "INFO",
  "component": "o.e.x.w.WatcherLifeCycleService",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "watcher has stopped and shutdown"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,375Z",
  "level": "INFO",
  "component": "o.e.x.m.p.l.CppLogMessageHandler",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "[controller/178] [Main.cc@174] ML controller exiting"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,376Z",
  "level": "INFO",
  "component": "o.e.x.m.p.NativeController",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "Native controller process has stopped - no new native processes can be started"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,499Z",
  "level": "INFO",
  "component": "o.e.n.Node",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "stopped"
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,499Z",
  "level": "INFO",
  "component": "o.e.n.Node",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "closing ..."
}
{
  "type": "server",
  "timestamp": "2022-03-31T21:39:10,510Z",
  "level": "INFO",
  "component": "o.e.n.Node",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "closed"
}
```

Relvant ECK Operator Logs
```json
{
  "log.level": "error",
  "@timestamp": "2022-03-31T21:53:19.544Z",
  "log.logger": "manager.eck-operator.controller.elasticsearch-controller",
  "message": "Reconciler error",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "name": "elasticsearch",
  "namespace": "elastic",
  "error": "unable to delete /_cluster/voting_config_exclusions: 503 Service Unavailable: ",
  "errorCauses": [
    {
      "error": "unable to delete /_cluster/voting_config_exclusions: 503 Service Unavailable: unknown",
      "errorVerbose": "503 Service Unavailable: unknown\nunable to delete /_cluster/voting_config_exclusions\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/client.(*clientV7).DeleteVotingConfigExclusions\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/client/v7.go:67\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/version/zen2.ClearVotingConfigExclusions\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/version/zen2/voting_exclusions.go:71\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).reconcileNodeSpecs\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/nodes.go:165\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:262\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:287\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:196\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
    }
  ],
  "error.stack_trace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:54:38.500Z",
  "log.logger": "generic-reconciler",
  "message": "Updating resource",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "kind": "ConfigMap",
  "namespace": "elastic-system",
  "name": "elastic-licensing"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:56:19.962Z",
  "log.logger": "elasticsearch-controller",
  "message": "Starting reconciliation run",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "iteration": 1422,
  "namespace": "elastic",
  "es_name": "elasticsearch"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:56:19.963Z",
  "log.logger": "generic-reconciler",
  "message": "Updating resource",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "kind": "Service",
  "namespace": "elastic",
  "name": "elasticsearch-es-transport"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:56:19.975Z",
  "log.logger": "generic-reconciler",
  "message": "Updating resource",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "kind": "Service",
  "namespace": "elastic",
  "name": "elasticsearch-es-http"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:56:38.500Z",
  "log.logger": "generic-reconciler",
  "message": "Updating resource",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "kind": "ConfigMap",
  "namespace": "elastic-system",
  "name": "elastic-licensing"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:57:00.264Z",
  "log.logger": "driver",
  "message": "Could not update cluster license",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "err": "while getting current license level 503 Service Unavailable: ",
  "namespace": "elastic",
  "es_name": "elasticsearch"
}
{
  "log.level": "error",
  "@timestamp": "2022-03-31T21:57:30.265Z",
  "log.logger": "driver",
  "message": "Could not update remote clusters in Elasticsearch settings",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "namespace": "elastic",
  "es_name": "elasticsearch",
  "error": "503 Service Unavailable: ",
  "error.stack_trace": "github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:215\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:287\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:196\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:57:30.279Z",
  "log.logger": "generic-reconciler",
  "message": "Updating resource",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "kind": "Service",
  "namespace": "elastic",
  "name": "elasticsearch-es-default"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:57:30.326Z",
  "log.logger": "zen2",
  "message": "Ensuring no voting exclusions are set",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "namespace": "elastic",
  "es_name": "elasticsearch"
}
{
  "log.level": "info",
  "@timestamp": "2022-03-31T21:58:00.327Z",
  "log.logger": "elasticsearch-controller",
  "message": "Ending reconciliation run",
  "service.version": "1.8.0+4f367c38",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "iteration": 1422,
  "namespace": "elastic",
  "es_name": "elasticsearch",
  "took": 100.364991016
}
```

**Comment by lui2131** [comment]
Update: Turns out that even after completely deleting the resource group this Elasticsearch cluster was in and then redeploying from scratch (with no existing PVC's) that the same errors persist.

**Comment by pebrc** [comment]
This sounds more like a networking problem in your k8s cluster and not necessarily something we can fix in the ECK operator?

Also: I would generally not recommend deleting the StatefulSets the operator creates. If you want to hard-restart individual Elasticsearch nodes delete the Pods, if you want to do a controlled restart of the whole cluster add a label to the `podTemplate` in the Elasticsearch manifest, if you want to remove the whole cluster delete the Elasticsearch resource.

**Comment by lui2131** [comment]
> This sounds more like a networking problem in your k8s cluster and not necessarily something we can fix in the ECK operator?
> 
> Also: I would generally not recommend deleting the StatefulSets the operator creates. If you want to hard-restart individual Elasticsearch nodes delete the Pods, if you want to do a controlled restart of the whole cluster add a label to the `podTemplate` in the Elasticsearch manifest, if you want to remove the whole cluster delete the Elasticsearch resource.

Thanks for the feedback on restarting the cluster, I will definitely utilize these strategies next time something happens and I need to troubleshoot.

As for the error I documented in this thread.  It turns out as you noted that this was a networking error.  This was related to the inter-pod communication between different pods in the same cluster failing.  This had to be addressed at the VNET/routing table level in order to fix the issue.

Will be closing this issue now.

Thanks
