### ISSUE TITLE
TestAgentVersionUpgradeToLatest8x/ES_data_should_pass_validations - 502 Bad Gateway-> Elastic Package Registry

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#5832]
```
=== RUN   TestAgentVersionUpgradeToLatest8x/ES_data_should_pass_validations
Retries (30m0s timeout): .............................................
 step.go:43: 
  Error Trace: utils.go:88
  Error: Received unexpected error:
    elasticsearch client failed for https://test-agent-upgrade-kvwd-es-internal-http.e2e-svc9x-mercury.svc:9200/_data_stream/logs-elastic_agent.filebeat-default: 404 Not Found:
    {Status:404 Error:{CausedBy:{Reason: Type:} Reason:no such index [logs-elastic_agent.filebeat-default] Type:index_not_found_exception RootCause:[{Reason:no such index [logs-elastic_agent.filebeat-default] Type:index_not_found_exception}]}}
```

Following of #5677. I think there were 2 different issues in #5677. The first which only happens in 7.17.3 (https://github.com/elastic/cloud-on-k8s/issues/5677#issuecomment-1144574134) which is fixed and another to find.

Historical:
| date     | stack version | missing index | test | job/build |
| ---------|---------------|-------|--------|-----------|
| 05-17 | 8.0.1  | logs-elastic_agent.filebeat-default     | TestAgentVersionUpgradeToLatest8x | stack/737 |
| 05-27 | 8.2.0 | logs-elastic_agent.filebeat-default | TestAgentVersionUpgradeToLatest8x | stack/761 |

**Comment by thbkrkr** [comment]
Looking at the diagnostic associated to https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-gke-k8s-versions/761/testReport, I'm seeing errors reaching the Elastic Package Registry during the Fleet setup, but it seems to have succeeded eventually. 

```
# Kibana log
[2022-06-27T02:08:19.954+00:00][ERROR][plugins.fleet] Error: [Elastic Agent on ECK policy] could not be added. [system] could not be installed due to error: [RegistryResponseError: '502 Bad Gateway' error response from package registry at https://epr.elastic.co/package/system/1.16.2]
    at /usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:212:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at ensurePreconfiguredPackagesAndPolicies (/usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:194:40)
    at createSetupSideEffects (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup.js:90:7)
    at awaitIfPending (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup_utils.js:38:20)
    at /usr/share/kibana/x-pack/plugins/fleet/server/plugin.js:273:9
[2022-06-27T02:08:19.954+00:00][WARN ][plugins.fleet] Fleet setup failed
[2022-06-27T02:08:19.954+00:00][WARN ][plugins.fleet] Error: [Elastic Agent on ECK policy] could not be added. [system] could not be installed due to error: [RegistryResponseError: '502 Bad Gateway' error response from package registry at https://epr.elastic.co/package/system/1.16.2]
    at /usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:212:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at ensurePreconfiguredPackagesAndPolicies (/usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:194:40)
    at createSetupSideEffects (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup.js:90:7)
    at awaitIfPending (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup_utils.js:38:20)
    at /usr/share/kibana/x-pack/plugins/fleet/server/plugin.js:273:9
[2022-06-27T02:08:19.965+00:00][INFO ][plugins.securitySolution] Dependent plugin setup complete - Starting ManifestTask
[2022-06-27T02:08:21.010+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-06-27T02:09:04.402+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-06-27T02:09:04.445+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-06-27T02:09:04.950+00:00][INFO ][plugins.fleet] Fleet setup completed
==== END logs for e2e-svc9x-mercury/test-agent-upgrade-m8db-kb-8459fb68cb-9h9bj ====
```

```
# Agent log
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Requesting service_token from Kibana.
Created service_token named: token-1656295670318
Performing setup of Fleet in Kibana

Kibana Fleet setup failed: http POST request to https://test-agent-upgrade-m8db-kb-http.e2e-svc9x-mercury.svc:5601/api/fleet/setup fails: [Elastic Agent on ECK policy] could not be added. [system] could not be installed due to error: [RegistryResponseError: '502 Bad Gateway' error response from package registry at https://epr.elastic.co/package/system/1.16.2]: <nil>. Response: {"statusCode":500,"error":"Internal Server Error","message":"[Elastic Agent on ECK policy] could not be added. [system] could not be installed due to error: [RegistryResponseError: '502 Bad Gateway' error response from package registry at https://epr... (truncated)
Policy selected for enrollment:  eck-agent
{"log.level":"info","@timestamp":"2022-06-27T02:09:05.504Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":461},"message":"Starting enrollment to URL: https://test-agent-upgrade-fs-smsh-agent-http.e2e-svc9x-mercury.svc:8220/","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-06-27T02:09:05.612Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":472},"message":"Remote server is not ready to accept connections, will retry in a moment.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:05.613Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":479},"message":"Retrying enrollment to URL: https://test-agent-upgrade-fs-smsh-agent-http.e2e-svc9x-mercury.svc:8220/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.169Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":259},"message":"Elastic Agent might not be running; unable to trigger restart","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.274Z","log.origin":{"file.name":"cmd/run.go","file.line":153},"message":"APM instrumentation disabled","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.275Z","log.origin":{"file.name":"application/application.go","file.line":78},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.276Z","log.origin":{"file.name":"application/application.go","file.line":102},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.276Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in /usr/share/elastic-agent/capabilities.yml","ecs.version":"1.6.0"}
I0627 02:10:06.795433     935 leaderelection.go:248] attempting to acquire leader lease e2e-svc9x-mercury/elastic-agent-cluster-leader...
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.897Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.898Z","log.logger":"composable.providers.kubernetes","log.origin":{"file.name":"kubernetes/kubernetes.go","file.line":90},"message":"Kubernetes provider started for resource pod with node scope","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:06.907Z","log.logger":"composable.providers.kubernetes","log.origin":{"file.name":"kubernetes/util.go","file.line":133},"message":"kubernetes: Node gke-eck-gke22-761-e2e-default-pool-712e5df0-1j45 discovered by in cluster pod node query","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:07.213Z","log.logger":"composable.providers.kubernetes","log.origin":{"file.name":"kubernetes/kubernetes.go","file.line":90},"message":"Kubernetes provider started for resource node with node scope","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:07.214Z","log.logger":"composable.providers.kubernetes","log.origin":{"file.name":"kubernetes/util.go","file.line":126},"message":"kubernetes: Using node gke-eck-gke22-761-e2e-default-pool-712e5df0-1j45 provided in the config","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:07.319Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":63},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:07.319Z","log.origin":{"file.name":"application/managed_mode.go","file.line":299},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-06-27T02:10:07.319Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":65},"message":"Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)","ecs.version":"1.6.0"}
==== END logs for e2e-svc9x-mercury/test-agent-upgrade-ea-mcdh-agent-qblbm ====
```

**Comment by thbkrkr** [comment]
Similar to:
- #5355

Related to:
- https://github.com/elastic/kibana/issues/131505
