### ISSUE TITLE
Stack Monitoring: Monitoring Request Failed Unable to find the cluster in the selected time range. UUID: xxxxxxxxxxx

### ISSUE THREAD

**Issue by duclm2609** [elastic/cloud-on-k8s#5928]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
I'm trying setting up stack monitoring using Metricbeats following tutorial at this [link](https://www.elastic.co/blog/elastic-stack-monitoring-with-elastic-cloud-on-kubernetes).

**What did you expect to see?**
Stack monitoring dashboard on Kibana.

**What did you see instead? Under which circumstances?**
Kibana pop up error: Monitoring Request Failed

Unable to find the cluster in the selected time range. UUID: xxxxxxxxxxxxxxx

**Environment**
EKS

* ECK version:
2.3.0

* Kubernetes information:
EKS v1.22
	

* Logs:
Kibana logs:
```
[2022-08-04T14:12:28.762+00:00][ERROR][plugins.monitoring.monitoring] Error: Unable to find the cluster in the selected time range. UUID: NqZBFfuIRZSnA4LGFP3Ptw
    at /usr/share/kibana/x-pack/plugins/monitoring/server/lib/cluster/get_cluster_stats.js:42:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/share/kibana/x-pack/plugins/monitoring/server/routes/api/v1/elasticsearch/nodes.js:58:30)
    at handler (/usr/share/kibana/x-pack/plugins/monitoring/server/plugin.js:359:28)
    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:163:30)
    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)
    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
```

I can see metrics data collected by Metricbeast under metricbeast-* index pattern.

**Comment by thbkrkr** [comment]
Hello,

It's likely that the recipes featured in the [blog post](https://www.elastic.co/blog/elastic-stack-monitoring-with-elastic-cloud-on-kubernetes) created 2 years ago will need some tweaking to work with the latest version of the Elastic Stack.

Since ECK 1.7.0, you can let ECK handle the Stack Monitoring configuration for you, see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html.

We try to keep GitHub issues only for real bug reports and feature requests specific to the ECK operator. Please create a topic in our discussion forum at https://discuss.elastic.co/ if you still want help with your Stack Monitoring issue.

**Comment by vojtechvelkjop** [comment]
Hi 
maybe it can help anyone. 
I had same issue on ECK and issue was due to  bad configuration in metricbeat kubernetes object.
bad host in : spec.config.metricbeat.providers.templates.config.hosts
