### ISSUE TITLE
Error registering Kibana Privileges with Elasticsearch for kibana-.kibana

### ISSUE THREAD

**Issue by cesarqdt** [elastic/cloud-on-k8s#5952]
## Bug Report
**What did you do?**
I have installed ECK via CRD 2.3 in my Kubernetes cluster (1.21) running in Azure. After I have deployed Elasticsearch and Kibana via the manifests shown below.

After a few minutes I can access to Kibana, the status for Kibana and Elasticsearch is in green, but when I check on the logs from Kibana I see many errors that you can check below:
```
[2022-08-12T18:40:23.349+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-08-12T18:40:23.362+00:00][INFO ][plugins.securitySolution] Dependent plugin setup complete - Starting ManifestTask
[2022-08-12T18:41:40.766+00:00][ERROR][plugins.security.authorization] Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: Request timed out
[2022-08-12T18:43:41.056+00:00][ERROR][plugins.security.authorization] Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: Request timed out
[2022-08-12T18:44:39.453+00:00][WARN ][plugins.usageCollection.usage-collection.collector-set] ResponseError: security_exception: [security_exception] Reason: action [indices:data/read/search] is unauthorized for service account [elastic/kibana], this action is granted by the index privileges [read,all]
    at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KibanaTransport.request (/usr/share/kibana/src/core/server/elasticsearch/client/create_transport.js:58:16)
    at ClientTraced.SearchApi [as search] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/search.js:65:12)
    at fetchClusters (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/alerts/fetch_clusters.js:53:20)
    at UsageCollector.fetch (/usr/share/kibana/x-pack/plugins/monitoring/server/kibana_monitoring/collectors/get_usage_collector.js:103:24)
    at CollectorSet.fetchCollector (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:146:24)
    at fetch_monitoring (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:175:107)
    at /usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:176:16
    at async Promise.all (index 46)
    at Object.bulkFetch (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:174:31)
    at getKibana (/usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_kibana.js:65:17)
    at async Promise.all (index 3)
    at /usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_local_stats.js:78:76
    at async Promise.all (index 0)
    at getLocalStats (/usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_local_stats.js:77:10)
    at async Promise.all (index 0)
    at Object.getStatsWithXpack [as statsGetter] (/usr/share/kibana/x-pack/plugins/telemetry_collection_xpack/server/telemetry_collection/get_stats_with_xpack.js:27:48)
    at TelemetryCollectionManagerPlugin.getUsageForCollection (/usr/share/kibana/src/plugins/telemetry_collection_manager/server/plugin.js:279:19)
    at TelemetryCollectionManagerPlugin.getStats (/usr/share/kibana/src/plugins/telemetry_collection_manager/server/plugin.js:213:29)
    at FetcherTask.fetchTelemetry (/usr/share/kibana/src/plugins/telemetry/server/fetcher.js:192:12)
    at FetcherTask.sendIfDue (/usr/share/kibana/src/plugins/telemetry/server/fetcher.js:88:18)
[2022-08-12T18:44:39.458+00:00][WARN ][plugins.usageCollection.usage-collection.collector-set] Unable to fetch data from monitoring collector
```

**What did you expect to see?**
No errors in Kibana and the platform working correctly.

**What did you see instead? Under which circumstances?**
Multiple errors as below

**Environment**
Azure Kubernetes 1.21

* ECK version:
(kubectl create -f https://download.elastic.co/downloads/eck/2.3.0/crds.yaml)
2.3.0
Kibana and Elasticsearch 

* Kubernetes information:
	* Cloud: Azure Kubernetes 1.21
	
	for each of them please give us the version you are using
```
$ kubectl version
1.21
```

* Resource definition:
```
# elasticsearch.yam
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.3.3
  nodeSets:
  - name: master-nodes
    count: 1
    config:
      node.roles: ["master"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: elasticsearch-azurefile
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        nodeSelector:
          agentpool: agentpool2
  - name: data-nodes
    count: 3
    config:
      node.roles: ["data", "ingest", "transform", "remote_cluster_client"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi
        storageClassName: elasticsearch-azurefile
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        nodeSelector:
          agentpool: agentpool2
# kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.3.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2
      nodeSelector:
        agentpool: agentpool2

```

* Logs:
```
# kubectl logs kibana-pod-name -f
>>>
[2022-08-12T18:39:12.669+00:00][INFO ][plugins-service] Plugin "cloudSecurityPosture" is disabled.
[2022-08-12T18:39:12.830+00:00][INFO ][http.server.Preboot] http server running at https://0.0.0.0:5601
[2022-08-12T18:39:12.875+00:00][INFO ][plugins-system.preboot] Setting up [1] plugins: [interactiveSetup]
[2022-08-12T18:39:12.914+00:00][WARN ][config.deprecation] The default mechanism for Reporting privileges will work differently in future versions, which will affect the behavior of this cluster. Set "xpack.reporting.roles.enabled" to "false" to adopt the future behavior before upgrading.
[2022-08-12T18:39:13.178+00:00][INFO ][plugins-system.standard] Setting up [118] plugins: [translations,monitoringCollection,licensing,globalSearch,globalSearchProviders,features,mapsEms,licenseApiGuard,usageCollection,taskManager,telemetryCollectionManager,telemetryCollectionXpack,share,embeddable,uiActionsEnhanced,screenshotMode,banners,newsfeed,fieldFormats,expressions,eventAnnotation,dataViews,charts,esUiShared,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,advancedSettings,spaces,security,lists,encryptedSavedObjects,cloud,snapshotRestore,screenshotting,telemetry,licenseManagement,kibanaUsageCollection,eventLog,actions,console,bfetch,data,watcher,reporting,fileUpload,ingestPipelines,alerting,aiops,unifiedSearch,savedObjects,triggersActionsUi,transform,stackAlerts,ruleRegistry,graph,savedObjectsTagging,savedObjectsManagement,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,controls,dataViewFieldEditor,visualizations,canvas,visTypeXy,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeHeatmap,visTypeMarkdown,dashboard,dashboardEnhanced,expressionXY,expressionTagcloud,expressionPartitionVis,visTypePie,expressionMetricVis,expressionHeatmap,expressionGauge,visTypeGauge,sharedUX,discover,lens,maps,dataVisualizer,ml,cases,timelines,sessionView,observability,fleet,synthetics,osquery,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,discoverEnhanced,dataViewManagement]
[2022-08-12T18:39:13.195+00:00][INFO ][plugins.taskManager] TaskManager is identified by the Kibana UUID: 7aa99426-170c-4bf5-baa4-d7a92e644cd4
[2022-08-12T18:39:13.421+00:00][WARN ][plugins.reporting.config] Found 'server.host: "0.0.0.0"' in Kibana configuration. Reporting is not able to use this as the Kibana server hostname. To enable PNG/PDF Reporting to work, 'xpack.reporting.kibanaServer.hostname: localhost' is automatically set in the configuration. You can prevent this message by adding 'xpack.reporting.kibanaServer.hostname: localhost' in kibana.yml.
[2022-08-12T18:39:13.445+00:00][INFO ][plugins.ruleRegistry] Installing common resources shared between all indices
[2022-08-12T18:39:14.352+00:00][INFO ][plugins.screenshotting.config] Chromium sandbox provides an additional layer of protection, and is supported for Linux Ubuntu 20.04 OS. Automatically enabling Chromium sandbox.
[2022-08-12T18:39:14.953+00:00][INFO ][savedobjects-service] Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
[2022-08-12T18:39:14.954+00:00][INFO ][savedobjects-service] Starting saved objects migrations
[2022-08-12T18:39:14.980+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with 'security_exception: [index_not_found_exception] Reason: no such index [.security]'. Retrying attempt 1 in 2 seconds.
[2022-08-12T18:39:14.980+00:00][INFO ][savedobjects-service] [.kibana_task_manager] INIT -> INIT. took: 8ms.
[2022-08-12T18:39:14.998+00:00][INFO ][savedobjects-service] [.kibana] INIT -> CREATE_NEW_TARGET. took: 29ms.
[2022-08-12T18:39:15.111+00:00][INFO ][plugins.screenshotting.chromium] Browser executable: /usr/share/kibana/x-pack/plugins/screenshotting/chromium/headless_shell-linux_x64/headless_shell
[2022-08-12T18:39:16.891+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [index_not_found_exception] Reason: no such index [.security]
[2022-08-12T18:39:16.985+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with 'security_exception: [index_not_found_exception] Reason: no such index [.security]'. Retrying attempt 2 in 4 seconds.
[2022-08-12T18:39:16.985+00:00][INFO ][savedobjects-service] [.kibana_task_manager] INIT -> INIT. took: 2006ms.
[2022-08-12T18:39:20.991+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with 'security_exception: [index_not_found_exception] Reason: no such index [.security]'. Retrying attempt 3 in 8 seconds.
[2022-08-12T18:39:20.992+00:00][INFO ][savedobjects-service] [.kibana_task_manager] INIT -> INIT. took: 4006ms.
[2022-08-12T18:39:23.280+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> MARK_VERSION_INDEX_READY. took: 8282ms.
[2022-08-12T18:39:24.210+00:00][INFO ][savedobjects-service] [.kibana] MARK_VERSION_INDEX_READY -> DONE. took: 930ms.
[2022-08-12T18:39:24.211+00:00][INFO ][savedobjects-service] [.kibana] Migration completed after 9242ms
[2022-08-12T18:39:29.007+00:00][INFO ][savedobjects-service] [.kibana_task_manager] INIT -> CREATE_NEW_TARGET. took: 8016ms.
[2022-08-12T18:39:29.392+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [index_not_found_exception] Reason: no such index [.security]
[2022-08-12T18:39:36.890+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> MARK_VERSION_INDEX_READY. took: 7883ms.
[2022-08-12T18:39:37.976+00:00][INFO ][savedobjects-service] [.kibana_task_manager] MARK_VERSION_INDEX_READY -> DONE. took: 1086ms.
[2022-08-12T18:39:37.976+00:00][INFO ][savedobjects-service] [.kibana_task_manager] Migration completed after 23005ms
[2022-08-12T18:39:37.983+00:00][INFO ][plugins-system.preboot] Stopping all plugins.
[2022-08-12T18:39:37.986+00:00][INFO ][plugins-system.standard] Starting [118] plugins: [translations,monitoringCollection,licensing,globalSearch,globalSearchProviders,features,mapsEms,licenseApiGuard,usageCollection,taskManager,telemetryCollectionManager,telemetryCollectionXpack,share,embeddable,uiActionsEnhanced,screenshotMode,banners,newsfeed,fieldFormats,expressions,eventAnnotation,dataViews,charts,esUiShared,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,advancedSettings,spaces,security,lists,encryptedSavedObjects,cloud,snapshotRestore,screenshotting,telemetry,licenseManagement,kibanaUsageCollection,eventLog,actions,console,bfetch,data,watcher,reporting,fileUpload,ingestPipelines,alerting,aiops,unifiedSearch,savedObjects,triggersActionsUi,transform,stackAlerts,ruleRegistry,graph,savedObjectsTagging,savedObjectsManagement,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,controls,dataViewFieldEditor,visualizations,canvas,visTypeXy,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeHeatmap,visTypeMarkdown,dashboard,dashboardEnhanced,expressionXY,expressionTagcloud,expressionPartitionVis,visTypePie,expressionMetricVis,expressionHeatmap,expressionGauge,visTypeGauge,sharedUX,discover,lens,maps,dataVisualizer,ml,cases,timelines,sessionView,observability,fleet,synthetics,osquery,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,discoverEnhanced,dataViewManagement]
[2022-08-12T18:39:39.007+00:00][INFO ][plugins.monitoring.monitoring] config sourced from: production cluster
[2022-08-12T18:39:40.317+00:00][INFO ][http.server.Kibana] http server running at https://0.0.0.0:5601
[2022-08-12T18:39:40.467+00:00][INFO ][plugins.monitoring.monitoring.kibana-monitoring] Starting monitoring stats collection
[2022-08-12T18:39:40.468+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-08-12T18:39:40.487+00:00][INFO ][status] Kibana is now degraded
[2022-08-12T18:39:53.763+00:00][INFO ][plugins.ml] Task ML:saved-objects-sync-task: scheduled with interval 1h
[2022-08-12T18:39:55.187+00:00][INFO ][plugins.ruleRegistry] Installed common resources shared between all indices
[2022-08-12T18:39:55.188+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.uptime.alerts
[2022-08-12T18:39:55.188+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-security.alerts
[2022-08-12T18:39:55.189+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .preview.alerts-security.alerts
[2022-08-12T18:39:55.190+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.logs.alerts
[2022-08-12T18:39:55.190+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.metrics.alerts
[2022-08-12T18:39:55.191+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.apm.alerts
[2022-08-12T18:39:57.205+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-security.alerts
[2022-08-12T18:39:57.207+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.metrics.alerts
[2022-08-12T18:39:57.207+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.logs.alerts
[2022-08-12T18:39:57.208+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.uptime.alerts
[2022-08-12T18:39:57.209+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.apm.alerts
[2022-08-12T18:39:59.816+00:00][INFO ][plugins.securitySolution.endpoint:metadata-check-transforms-task:0.0.1] no endpoint installation found
[2022-08-12T18:39:59.852+00:00][INFO ][status] Kibana is now available (was degraded)
[2022-08-12T18:40:02.253+00:00][INFO ][plugins.reporting.store] Creating ILM policy for managing reporting indices: kibana-reporting
[2022-08-12T18:40:11.551+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .preview.alerts-security.alerts
[2022-08-12T18:40:13.131+00:00][INFO ][status] Kibana is now degraded (was available)
[2022-08-12T18:40:18.116+00:00][INFO ][status] Kibana is now available (was degraded)
[2022-08-12T18:40:23.337+00:00][INFO ][plugins.ml] Task ML:saved-objects-sync-task: 1 ML saved object synced
[2022-08-12T18:40:23.349+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-08-12T18:40:23.362+00:00][INFO ][plugins.securitySolution] Dependent plugin setup complete - Starting ManifestTask
[2022-08-12T18:41:40.766+00:00][ERROR][plugins.security.authorization] Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: Request timed out
[2022-08-12T18:43:41.056+00:00][ERROR][plugins.security.authorization] Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: Request timed out
[2022-08-12T18:44:39.453+00:00][WARN ][plugins.usageCollection.usage-collection.collector-set] ResponseError: security_exception: [security_exception] Reason: action [indices:data/read/search] is unauthorized for service account [elastic/kibana], this action is granted by the index privileges [read,all]
    at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KibanaTransport.request (/usr/share/kibana/src/core/server/elasticsearch/client/create_transport.js:58:16)
    at ClientTraced.SearchApi [as search] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/search.js:65:12)
    at fetchClusters (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/alerts/fetch_clusters.js:53:20)
    at UsageCollector.fetch (/usr/share/kibana/x-pack/plugins/monitoring/server/kibana_monitoring/collectors/get_usage_collector.js:103:24)
    at CollectorSet.fetchCollector (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:146:24)
    at fetch_monitoring (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:175:107)
    at /usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:176:16
    at async Promise.all (index 46)
    at Object.bulkFetch (/usr/share/kibana/src/plugins/usage_collection/server/collector/collector_set.js:174:31)
    at getKibana (/usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_kibana.js:65:17)
    at async Promise.all (index 3)
    at /usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_local_stats.js:78:76
    at async Promise.all (index 0)
    at getLocalStats (/usr/share/kibana/src/plugins/telemetry/server/telemetry_collection/get_local_stats.js:77:10)
    at async Promise.all (index 0)
    at Object.getStatsWithXpack [as statsGetter] (/usr/share/kibana/x-pack/plugins/telemetry_collection_xpack/server/telemetry_collection/get_stats_with_xpack.js:27:48)
    at TelemetryCollectionManagerPlugin.getUsageForCollection (/usr/share/kibana/src/plugins/telemetry_collection_manager/server/plugin.js:279:19)
    at TelemetryCollectionManagerPlugin.getStats (/usr/share/kibana/src/plugins/telemetry_collection_manager/server/plugin.js:213:29)
    at FetcherTask.fetchTelemetry (/usr/share/kibana/src/plugins/telemetry/server/fetcher.js:192:12)
    at FetcherTask.sendIfDue (/usr/share/kibana/src/plugins/telemetry/server/fetcher.js:88:18)
[2022-08-12T18:44:39.458+00:00][WARN ][plugins.usageCollection.usage-collection.collector-set] Unable to fetch data from monitoring collector
[2022-08-12T19:40:15.406+00:00][INFO ][plugins.ml] Task ML:saved-objects-sync-task: No ML saved objects in need of synchronization
[2022-08-12T20:12:17.214+00:00][INFO ][plugins.security.routes] Logging in with provider "basic" (basic)
[2022-08-12T20:12:43.190+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-08-12T20:12:43.247+00:00][INFO ][plugins.fleet] Fleet setup completed
```

**Comment by naemono** [comment]
@cesarqdt I knew this error sounded familiar, but the presence of `service account` threw me off, as I though it may have had something to do with the recent move to using service accounts for Kibana => Elasticsearch communication.  That was not the case.  

See https://github.com/elastic/kibana/issues/125756

Ignore the fact that you're seeing this outside of the stack monitoring kibana page, but update your Kibana configuration to this:

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  config:
    monitoring.ui.ccs.enabled: false
```

Let me Kibana pod restart, and you should be able to login and this error goes away.  

I also think you could add `remote_cluster_client` to the master nodeset roles as well to resolve this.

I'm going to go ahead and close this issue, as this isn't an ECK issue, but a Kibana issue.

**Comment by dlukyanov** [comment]
I was using docker-compose.yaml from this instruction with `STACK_VERSION=8.9.0`
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-file


where kibana service defined like this:

```
  kibana:
    depends_on:
      ...
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
```

And faced exactly the same problem as defined in subject
```
[ERROR][plugins.security.authorization]
    Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: Request timed out
```
Then i figured out that kibana container already has definition of `elasticsearch.hosts` in `$HOME/congig/kibana.yml`

Adding one line into `environment` fixed the problem (at least partially):
```
      - elasticsearch.hosts=https://es01:9200
```

Note that the same docker-compose.yaml file works fine with `STACK_VERSION=7.17.10`
