### ISSUE TITLE
Elasticsearch fails to start: cannot create elasticsearch.keystore.tmp

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#643]
Seems to happen randomly. This is preventing the Elasticsearch pod from correctly starting the first time.

```
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
```

Full logs:

```
{"level":"info","ts":1555421135.6005945,"logger":"keystore-updater","msg":"Wait for reloading credentials"}
{"level":"info","ts":1555421135.6008117,"logger":"keystore-updater","msg":"Creating keystore","keystore-path":"/usr/share/elasticsearch/config/elasticsearch.keystore"}
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"level":"error","ts":1555421143.7436311,"logger":"keystore-updater","msg":"Cannot update keystore","msg":"could not create new keystore","error":"exit status 1","stacktrace":"github.com/elastic/k8s-operators/operators/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/keystore.(*Updater).watchForUpdate\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/keystore/updater.go:100"}
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
Likely root cause: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:222)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:411)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:407)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:255)
        at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:467)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:238)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:295)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
Refer to the log for complete error details.
{"level":"info","ts":1555421144.467077,"logger":"process-manager","msg":"Process liveness check","action":"wait","state":"started","alive":false,"err":"no such process"}
{"level":"info","ts":1555421144.467242,"logger":"process-manager","msg":"Process terminated","action":"wait","state":"started","alive":false,"err":"exit status 1"}
{"level":"info","ts":1555421144.467262,"logger":"process-manager","msg":"Update process state","action":"wait","id":"es","state":"failed","pid":15,"err":"exit status 1"}
{"level":"info","ts":1555421144.4672797,"logger":"process-manager","msg":"Graceful exit","reason":"unexpected state: process terminated without stop/kill","err":"exit status 1"}
{"level":"info","ts":1555421144.4672863,"logger":"process-manager","msg":"Process liveness check","action":"graceful exit","state":"failed","alive":false,"err":"no such process"}
{"level":"info","ts":1555421144.4673066,"logger":"process-manager","msg":"Exited"}
```

**Comment by nithril** [comment]
I got the issue using the 0.8.0. #631 seems to be included in the 0.8.0

**Comment by sebgl** [comment]
Let's reopen, thanks for reporting @nithril! Do you still happen to have the error logs?

**Comment by nithril** [comment]
I have that log from the pod in error:
```
{"level":"info","ts":1558610473.924607,"logger":"process-manager","msg":"Update process state","action":"initialization","id":"es","state":"failed","pid":0}
{"level":"info","ts":1558610473.9247065,"logger":"process-manager","msg":"Starting..."}
{"level":"info","ts":1558610473.9254303,"logger":"process-manager","msg":"Update process state","action":"start","id":"es","state":"started","pid":14}
{"level":"info","ts":1558610473.9254875,"logger":"process-manager","msg":"Started"}
{"level":"info","ts":1558610473.9313762,"logger":"keystore-updater","msg":"Waiting for Elasticsearch to be ready"}
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
Likely root cause: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:222)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:411)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:407)
	at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:255)
	at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:462)
	at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:232)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:289)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Refer to the log for complete error details.
{"level":"info","ts":1558610475.5319855,"logger":"process-manager","msg":"Update process state","action":"terminate","id":"es","state":"failed","pid":14}
{"level":"info","ts":1558610475.5322087,"logger":"process-manager","msg":"Exit","reason":"process failed","code":1}
```

Unfortunately, I have already deleted the pod, it has been then recreated successfully.

**Comment by iekulyk** [comment]
Having this issue almost on all pods, started to appear after a few minutes of es cluster run. Can provide logs if needed

**Comment by zanoubia** [comment]
Same thing here! Elasticsearch run for some minutes then a CrashLoopBackOff, with the following logs in the pod:

`
{"level":"info","ts":1561636379.3319728,"logger":"keystore-updater","msg":"Waiting for Elasticsearch to be ready"}
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
Likely root cause: java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:222)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:411)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:407)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:255)
        at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:462)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:242)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:305)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Refer to the log for complete error details.
{"level":"info","ts":1561636381.358021,"logger":"process-manager","msg":"Update process state","action":"terminate","id":"es","state":"failed","pid":14}
{"level":"info","ts":1561636381.3581822,"logger":"process-manager","msg":"Exit","reason":"process failed","code":1}


`

**Comment by pebrc** [comment]
Hm interesting, I wonder what is going on there. The keystore updater waits since #631 until Elasticsearch responds to requests via the API. Maybe we have a bug in the waiting logic. 

What I think is happening here is: 
* Elasticsearch Bootstrap runs, tries to load the secure settings
* sees that there is no keystore file and creates an empty one (that involves writing to the `.tmp` file first and then moving it into place 
* some other process does the same concurrently (most likely our keystore updater) and Elasticsearch  fails to create the tmp file because it is there already. 

Some things to check: 
* is there for some reason just the `.tmp` file but not the actual file in place?
* does our waiting logic in the keystore updater work?

Potential improvement: 
* wait with the keystore updater until Elasticsearch has written the initial keystore (just check for the file's existence instead of calling the API)

**Comment by zanoubia** [comment]
Thank you for your prompt reply.
Any chance to use a workaround to make it work ? What version of image should I use meanwhile ?

**Comment by sebgl** [comment]
Release `0.9` that should be out in a few weeks will change the way we deal with keystore updates, to rely on an init container instead.
Chances are this will fix this issue.

I'll close this one now, let's reopen if the bug is still there in 0.9.
