### ISSUE TITLE
TestFleet*/ES_data_should_pass_validations flaky

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6679]
Since we re-enabled Fleet* e2e testing and have a working nightly pipeline, `TestFleetAgentWithoutTLS` and `TestFleetMode` have failed several times. Tests run on GKE k8s v1.25.

* `TestFleetAgentWithoutTLS/ES_data_should_pass_validations` ~ stack-8.4.3 [build/134](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/134#018732b0-e407-4265-9876-4765a750fff1)
* `TestFleetAgentWithoutTLS/ES_data_should_pass_validations` ~ stack 8.0.1 [build/135](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/135#018737d0-1fb1-46fc-8a89-52e00dd5eb82)
* `TestFleetMode/ES_data_should_pass_validations` ~ stack-8.8.0-SNAPSHOT [build/143](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/143#01876102-8db5-4a6a-ab06-fdf43727aeb2)
* `TestFleetMode/ES_data_should_pass_validations` ~ stack-8.1.3 [builds/144](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/144#01876628-2a1e-4e71-a391-2b1b6565f9f3)
* `TestFleetMode/ES_data_should_pass_validations` ~ stack-8.8.0-SNAPSHOT [build/144](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/144#01876628-2a2a-425d-81a5-02d4531817f6)
* `TestFleetAgentWithoutTLS/ES_data_should_pass_validations` ~ stack-8.8.0-SNAPSHOT [build/144](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/144#01876628-2a2a-425d-81a5-02d4531817f6)
* `TestFleetMode/ES_data_should_pass_validations` ~ stack-8.8.0-SNAPSHOT [build/146](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/146#01877079-f581-4ea6-9a97-34aac2cd0792)
* `TestFleetAgentWithoutTLS/ES_data_should_pass_validations` ~ stack-8.8.0-SNAPSHOT [build/146](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/146#01877079-f581-4ea6-9a97-34aac2cd0792)

**Comment by barkbay** [comment]
## TestFleetMode/ES_data_should_pass_validations ~ stack-8.1.3 [builds/144](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/144#01876628-2a1e-4e71-a391-2b1b6565f9f3)

`pod/test-agent-fleet-fs-57jd-agent-5dd599f996-pf4dg` is not able to connect to itself?

```json
{
	"log.level": "error",
	"@timestamp": "2023-04-09T21:22:14.681Z",
	"log.origin": {
		"file.name": "fleet/fleet_gateway.go",
		"file.line": 206
	},
	"message": "Could not communicate with fleet-server Checking API will retry, error: fail to checkin to fleet-server: Post \"https://test-agent-fleet-fs-57jd-agent-http.e2e-286l8-mercury.svc:8220/api/fleet/agents/c1434379-1c4c-4ff3-8acb-4e74251541e9/checkin?\": dial tcp 10.92.190.130:8220: connect: connection refused",
	"ecs.version": "1.6.0"
}
```

Agents are failing with:

```json
{
	"log.level": "info",
	"@timestamp": "2023-04-09T21:12:05.227Z",
	"log.origin": {
		"file.name": "cmd/enroll_cmd.go",
		"file.line": 473
	},
	"message": "Retrying enrollment to URL: https://test-agent-fleet-fs-57jd-agent-http.e2e-286l8-mercury.svc:8220/",
	"ecs.version": "1.6.0"
}
```
```json
{
	"log.level": "warn",
	"@timestamp": "2023-04-09T21:12:05.334Z",
	"log.origin": {
		"file.name": "cmd/enroll_cmd.go",
		"file.line": 466
	},
	"message": "Remote server is not ready to accept connections, will retry in a moment.",
	"ecs.version": "1.6.0"
}
```

**Comment by barkbay** [comment]
## TestFleetAgentWithoutTLS/ES_data_should_pass_validations ~ stack 8.0.1 [build/135](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/135#018737d0-1fb1-46fc-8a89-52e00dd5eb82)

Two E2E tests have failed on that cluster:
#### 1. TestAPMServerVersionUpgradeToLatest8x

```
{"Time":"2023-03-31T15:07:35.918701197Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v2/test/e2e/apm","Test":"TestAPMServerVersionUpgradeToLatest8x/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process","Output":"    --- FAIL: TestAPMServerVersionUpgradeToLatest8x/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process (0.00s)\n"}

{"Time":"2023-03-31T15:07:35.918713795Z","Action":"fail","Package":"github.com/elastic/cloud-on-k8s/v2/test/e2e/apm","Test":"TestAPMServerVersionUpgradeToLatest8x/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process","Elapsed":0}
```

#### 2. TestFleetAgentWithoutTLS

```
{"Time":"2023-03-31T14:52:34.149059977Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v2/test/e2e/agent","Test":"TestFleetAgentWithoutTLS/ES_data_should_pass_validations","Output":"    --- FAIL: TestFleetAgentWithoutTLS/ES_data_should_pass_validations (1800.00s)\n"}

{"Time":"2023-03-31T14:52:34.149099055Z","Action":"fail","Package":"github.com/elastic/cloud-on-k8s/v2/test/e2e/agent","Test":"TestFleetAgentWithoutTLS/ES_data_should_pass_validations","Elapsed":1800}
```

It seems that the resources for the 2 different tests were running at the same time according to the diagnostic, for example there are 2 `Elasticsearch` resources:

* `apmserver-upgrade-bw9b`
* `test-fleet-agent-notls-2zqg`

And 11 `Pods`:

* `apmserver-upgrade-bw9b-es-masterdata-0`
* `apmserver-upgrade-bw9b-es-masterdata-1`
* `apmserver-upgrade-bw9b-es-masterdata-2`
* `apmserver-upgrade-ttvw-apm-server-7bd75dbcc-cjrlk`
* `test-fleet-agent-notls-2zqg-es-masterdata-0`
* `test-fleet-agent-notls-2zqg-es-masterdata-1`
* `test-fleet-agent-notls-2zqg-es-masterdata-2`
* `test-fleet-agent-notls-ea-2hjn-agent-4jjqn`
* `test-fleet-agent-notls-ea-2hjn-agent-sgd8f`
* `test-fleet-agent-notls-ea-2hjn-agent-tf8kz`
* `test-fleet-agent-notls-fs-4jzt-agent-cf4779dbd-wwl94`
* `test-fleet-agent-notls-lqmh-kb-5fc4d4c874-zbjvf`

Regarding `TestFleetAgentWithoutTLS` it seems that the Agent started as expected, there is no obvious error in the logs, `health` is `green`, associations are `Established` and some indices have been successfully created and some documents have been indexed:

```
health status index                                                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size sth
green  open   .apm-agent-configuration                                          Fmtys0U6ToCtC3qh_D4pVg   1   1          0            0       450b           225b false
green  open   .apm-custom-link                                                  CWHQsSaWTC2rON-H9pfWFg   1   1          0            0       450b           225b false
green  open   .ds-ilm-history-5-2023.03.31-000001                               5Ym72CeYTFORV8mG0K9mXw   1   1         18            0       61kb         30.5kb false
green  open   .ds-logs-elastic_agent-default-2023.03.31-000001                  582ed_sySS2F24hXWYjdSw   1   1        108            0    683.5kb        353.6kb false
green  open   .ds-logs-elastic_agent.fleet_server-default-2023.03.31-000001     -BVAJAneSr6KOBNibe0lMw   1   1        229            0    482.6kb        195.8kb false
green  open   .ds-metrics-elastic_agent.elastic_agent-default-2023.03.31-000001 bgPtBsXoRCKgysy5obnsAA   1   1       4856            0        1mb        598.1kb false
green  open   .ds-metrics-elastic_agent.fleet_server-default-2023.03.31-000001  P9RQ9I_YTs2Q36_hI2gB7A   1   1       2428            0    375.3kb        213.6kb false
green  open   .fleet-agents-7                                                   V_l2lHOLQUqE7-ZLTAfLoQ   1   1          4         3361      1.5mb        729.6kb false
green  open   .fleet-enrollment-api-keys-7                                      AEGBxQ96RzSHFSvinrcNmA   1   1          2            0     13.3kb          6.6kb false
green  open   .fleet-policies-7                                                 e-fdUPLfQLKdjQ1Wvcfc8Q   1   1          4            0     39.4kb         19.7kb false
green  open   .fleet-policies-leader-7                                          4qHwQxM-RV6S3YGu07dKlA   1   1          2         2256    198.1kb         94.1kb false
green  open   .fleet-servers-7                                                  9GOsboHdTYyBG_v4C6oSrQ   1   1          1            2     82.8kb         41.3kb false
green  open   .geoip_databases                                                  z3RD405WQK27hU9s9NfyIw   1   1         42            0       81mb         40.5mb false
green  open   .kibana-event-log-8.0.1-000001                                    XwtNcBjfSCCDGkrFqjl63g   1   1          1            0     12.5kb          6.2kb false
green  open   .kibana_8.0.1_001                                                 rFKm6rNSRrSe9qEy-zsASg   1   1       2458            1     14.3mb          7.1mb false
green  open   .kibana_security_session_1                                        PxDwqBZiQLaoH7SrLnn1jg   1   1          0            0       450b           225b false
green  open   .kibana_task_manager_8.0.1_001                                    sT5dk6d4TCa6tS0X48daiw   1   1         18        21213      4.8mb          2.4mb false
green  open   .security-7                                                       UPARpDFYR_uQbOipgMq4QA   1   1        111          128    969.2kb        484.6kb false
```
_( ⬆️ from `eck-diagnostics-2023-03-31T21-06-53/e2e-3szjm-mercury/elasticsearch/test-fleet-agent-notls-2zqg/cat/cat_indices.txt`)_

Still investigating...

**Comment by naemono** [comment]
So I encountered this again and noticed this in the Kibana logs:

```
[2023-05-23T14:17:25.315+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2023-05-23T14:17:25.330+00:00][INFO ][plugins.monitoring.monitoring] config sourced from: production cluster
[2023-05-23T14:17:26.665+00:00][INFO ][http.server.Kibana] http server running at http://0.0.0.0:5601
[2023-05-23T14:17:26.911+00:00][INFO ][plugins.monitoring.monitoring.kibana-monitoring] Starting monitoring stats collection
[2023-05-23T14:17:27.759+00:00][INFO ][plugins.ruleRegistry] Installed common resources shared between all indices
[2023-05-23T14:17:27.759+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.uptime.alerts
[2023-05-23T14:17:27.760+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-security.alerts
[2023-05-23T14:17:27.760+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .preview.alerts-security.alerts
[2023-05-23T14:17:27.760+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.logs.alerts
[2023-05-23T14:17:27.760+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.metrics.alerts
[2023-05-23T14:17:27.761+00:00][INFO ][plugins.ruleRegistry] Installing resources for index .alerts-observability.apm.alerts
[2023-05-23T14:17:27.956+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-security.alerts
[2023-05-23T14:17:28.025+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.uptime.alerts
[2023-05-23T14:17:28.077+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.logs.alerts
[2023-05-23T14:17:28.123+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.apm.alerts
[2023-05-23T14:17:28.170+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .alerts-observability.metrics.alerts
[2023-05-23T14:17:28.505+00:00][INFO ][status] Kibana is now degraded
[2023-05-23T14:17:28.833+00:00][INFO ][plugins.ruleRegistry] Installed resources for index .preview.alerts-security.alerts
[2023-05-23T14:17:30.442+00:00][INFO ][plugins.securitySolution.endpoint:metadata-check-transforms-task:0.0.1] no endpoint metadata transforms found
[2023-05-23T14:17:33.981+00:00][WARN ][plugins.fleet] Failure to install package [kubernetes]: [Error: Encountered 2 errors creating saved objects: [{"type":"index-pattern","id":"logs-*","error":{"type":"conflict"}},{"type":"index-pattern","id":"metrics-*","error":{"type":"conflict"}}]]
[2023-05-23T14:17:33.982+00:00][ERROR][plugins.fleet] uninstalling kubernetes-1.17.3 after error installing: [Error: Encountered 2 errors creating saved objects: [{"type":"index-pattern","id":"logs-*","error":{"type":"conflict"}},{"type":"index-pattern","id":"metrics-*","error":{"type":"conflict"}}]]
[2023-05-23T14:17:36.773+00:00][ERROR][plugins.fleet] failed to uninstall or rollback package after installation error Error: Saved object [epm-packages/kubernetes] not found
[2023-05-23T14:17:37.398+00:00][INFO ][status] Kibana is now available (was degraded)
[2023-05-23T14:17:37.413+00:00][INFO ][plugins.reporting.store] Creating ILM policy for managing reporting indices: kibana-reporting
[2023-05-23T14:17:52.123+00:00][WARN ][plugins.fleet] Failed installing package [kubernetes] due to error: [Error: Encountered 2 errors creating saved objects: [{"type":"index-pattern","id":"logs-*","error":{"type":"conflict"}},{"type":"index-pattern","id":"metrics-*","error":{"type":"conflict"}}]]
[2023-05-23T14:17:56.319+00:00][WARN ][plugins.fleet] Fleet setup failed
[2023-05-23T14:17:56.319+00:00][WARN ][plugins.fleet] Error: [Elastic Agent on ECK policy] could not be added. [kubernetes] could not be installed due to error: [Error: Encountered 2 errors creating saved objects: [{"type":"index-pattern","id":"logs-*","error":{"type":"conflict"}},{"type":"index-pattern","id":"metrics-*","error":{"type":"conflict"}}]]
    at /usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:293:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at ensurePreconfiguredPackagesAndPolicies (/usr/share/kibana/x-pack/plugins/fleet/server/services/preconfiguration.js:275:40)
    at createSetupSideEffects (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup.js:88:7)
    at awaitIfPending (/usr/share/kibana/x-pack/plugins/fleet/server/services/setup_utils.js:38:20)
    at /usr/share/kibana/x-pack/plugins/fleet/server/plugin.js:243:9
```

Agent status' are all `Green`, connections with Elasticsearch `Established` logs are clean and ES indices seem fine:

```
health status index                                                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size sth
green  open   .apm-agent-configuration                                          YXqC9jExRH2YvNnd5EnpTA   1   1          0            0       450b           225b false
green  open   .apm-custom-link                                                  BEYbq_0_QOeM13JS3FoF_w   1   1          0            0       450b           225b false
green  open   .ds-ilm-history-5-2023.05.23-000001                               cXk87jSRShuPgoP9XZ_e_g   1   1         18            0     60.9kb         30.4kb false
green  open   .ds-logs-elastic_agent-default-2023.05.23-000001                  p--6Ar4wRbOND96fTUIaYA   1   1        105            0    644.6kb        335.1kb false
green  open   .ds-logs-elastic_agent.fleet_server-default-2023.05.23-000001     2_oRuoadRDKlOn7O-I6AgA   1   1        234            0    420.6kb        186.2kb false
```

**Comment by thbkrkr** [comment]
Closing because all `TestFleet*/ES_data_should_pass_validations` pass in `8.8.0` since more than a month.
